#!/bin/bash

set -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

output=${output:-signalfx-agent.tar.gz}
output_tar=$(basename $output .gz)

TAG=standalone make image

cid=$(docker create quay.io/signalfuse/signalfx-agent:standalone true)
trap "docker rm -f $cid; rm -f $output_tar" EXIT

docker export $cid > $output_tar
tar -C $SCRIPT_DIR -rf $output_tar run
gzip $output_tar
