#!/bin/bash

set -ex

script_dir() {
  cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd
}

. $(script_dir)/../common.sh

OUTPUT=${OUTPUT:-signalfx-agent.tar.gz}

if [ -n "${BUILD_BRANCH}" ]; then
  TAG=${TAG:-$BUILD_BRANCH}
else
  TAG=${TAG:-$USER}
fi

image=signalfx-agent-standalone:$TAG
output_tar=$(basename $OUTPUT .gz)

do_docker_build $image standalone

cid=$(docker create $image true)
tmpdir=$(mktemp -d)
trap "docker rm -f $cid; rm -rf $tmpdir; rm -f $output_tar" EXIT

docker export $cid | tar -C $tmpdir -xf -
rm -rf $tmpdir/{proc,sys,dev,etc} $tmpdir/.dockerenv
tar -C $tmpdir -zcf $output_tar.gz .
