{{- if and .Values.podDisruptionBudget .Values.isServerless }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "signalfx-agent.fullname" . }}
  namespace: {{ template "signalfx-agent.namespace" . }}
  labels:
    app: {{ template "signalfx-agent.name" . }}
    chart: {{ template "signalfx-agent.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "signalfx-agent.name" . }}
      release: {{ .Release.Name }}
{{ toYaml .Values.podDisruptionBudget | trim | indent 2 }}
{{- end }}
