{{ if not .Values.signalFxAccessTokenSecretName}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "signalfx-agent.fullname" . }}
  namespace: {{ template "signalfx-agent.namespace" . }}
  labels:
    app: {{ template "signalfx-agent.name" . }}
    chart: {{ template "signalfx-agent.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  access-token: {{ (required ".Values.signalFxAccessToken is required. If you need an access token, check your profile page in the SignalFx web application, or visit https://www.signalfx.com for a free trial." .Values.signalFxAccessToken) | b64enc | quote }}
{{end}}
