monitors:
- monitorType: prometheus/nginx-vts
  doc: |
    This monitor scrapes [Prmoetheus Nginx VTS
    exporter](https://github.com/hnlq715/nginx-vts-exporter) metrics from a
    Prometheus exporter and sends them to SignalFx.  It is a wrapper around the
    [prometheus-exporter](./prometheus-exporter.md) monitor that provides a
    restricted but expandable set of metrics.
  metrics:
    nginx_vts_info:
      description: Nginx info
      included:
      type: gauge
    nginx_vts_start_time_seconds:
      description: Nginx start time
      included:
      type: gauge
    nginx_vts_main_connections:
      description: connections
      included: true
      type: gauge
    nginx_vts_main_shm_usage_bytes:
      description: Shared memory [ngx_http_vhost_traffic_status] info
      included:
      type: gauge
    nginx_vts_server_bytes_total:
      description: The request/response bytes
      included:
      type: cumulative
    nginx_vts_server_requests_total:
      description: The requests counter
      included: true
      type: cumulative
    nginx_vts_server_request_seconds_total:
      description: The request processing time in seconds
      included:
      type: cumulative
    nginx_vts_server_cache_total:
      description: The requests cache counter
      included:
      type: cumulative
    nginx_vts_server_request_seconds:
      description: The average of request processing times in seconds
      included: true
      type: gauge
    nginx_vts_server_request_duration_seconds:
      description: The histogram of request processing time
      included:
      type: cumulative
    nginx_vts_upstream_bytes_total:
      description: The request/response bytes
      included:
      type: cumulative
    nginx_vts_upstream_requests_total:
      description: The upstream requests counter
      included:
      type: cumulative
    nginx_vts_upstream_request_seconds_total:
      description: The request Processing time including upstream in seconds
      included:
      type: cumulative
    nginx_vts_upstream_request_seconds:
      description: The average of request processing times including upstream in seconds
      included: true
      type: gauge
    nginx_vts_upstream_response_seconds_total:
      description: The only upstream response processing time in seconds
      included:
      type: cumulative
    nginx_vts_upstream_response_seconds:
      description: The average of only upstream response processing times in seconds
      included:
      type: gauge
    nginx_vts_upstream_request_duration_seconds:
      description: The histogram of request processing time including upstream
      included:
      type: cumulative
    nginx_vts_upstream_response_duration_seconds:
      description: The histogram of only upstream response processing time
      included:
      type: cumulative
