---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-deployment
  labels:
    app: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
        - name: couchbase
          image: couchbase:test
          ports:
            - containerPort: 8091
          env:
            - name: USERNAME
              value: administrator
            - name: PASSWORD
              value: testing123
          readinessProbe:
            httpGet:
              path: /pools/default
              port: 8091
              httpHeaders:
                - name: Authorization
                  value: Basic YWRtaW5pc3RyYXRvcjp0ZXN0aW5nMTIz
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
