#!/bin/bash

set -euxo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT_DIR/../code-gen-helpers.sh

#json_file="/tmp/agent.json"

ensure_description_json

gomplate --file $SCRIPT_DIR/templates/monitor-main.md.tmpl --datasource agent=$json_file > $SCRIPT_DIR/../../docs/monitor-config.md

mon_dir=$SCRIPT_DIR/../../docs/monitors
mkdir -p $mon_dir

for i in $(seq 0 $(($(j '.Monitors | length')-1))); do
  monitorType=$(j ".Monitors[$i].monitorType")

  j ".Monitors[$i]" | gomplate --file $SCRIPT_DIR/templates/monitor-page.md.tmpl --datasource monitor=stdin:///monitor.json > $mon_dir/${monitorType//\//-}.md
done
