#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT_DIR/../code-gen-helpers.sh

generate_selfdescribe_json

j "." | \
  inject_to_obj "doc_types" "$doc_types" | \
  gomplate --file $SCRIPT_DIR/templates/monitor-main.md.tmpl --datasource agent=stdin:///agent.json > $SCRIPT_DIR/../../docs/monitor-config.md

j "." | \
  inject_to_obj "doc_types" "$doc_types" | \
  gomplate --file $SCRIPT_DIR/templates/observer-main.md.tmpl --datasource agent=stdin:///agent.json > $SCRIPT_DIR/../../docs/observer-config.md

j "." | \
  inject_to_obj "doc_types" "$doc_types" | \
  gomplate --file $SCRIPT_DIR/templates/top-config.md.tmpl --datasource agent=stdin:///agent.json > $SCRIPT_DIR/../../docs/config-schema.md

obs_dir=$SCRIPT_DIR/../../docs/observers
mkdir -p $obs_dir

for i in $(seq 0 $(($(j '.Observers | length')-1))); do
  observerType=$(j ".Observers[$i].observerType")

  j ".Observers[$i]" |\
    inject_to_obj "doc_types" "$doc_types" | \
    gomplate --file $SCRIPT_DIR/templates/observer-page.md.tmpl --datasource observer=stdin:///observer.json > $obs_dir/${observerType//\//-}.md
done

j ".Monitors[].monitorType" | xargs -P${NUM_CORES} -I% -n1 scripts/make-monitor-doc %
