monitors:
- metrics:
    haproxy_process_nbthread:
      default: false
      description: Configured number of threads.
      type: gauge
    haproxy_process_nbproc:
      default: false
      description: Configured number of processes.
      type: gauge
    haproxy_process_relative_process_id:
      default: false
      description: Relative process id, starting at 1.
      type: gauge
    haproxy_process_start_time_seconds:
      default: false
      description: Start time in seconds.
      type: gauge
    haproxy_process_max_memory_bytes:
      default: false
      description: Per-process memory limit (in bytes); 0=unset.
      type: gauge
    haproxy_process_pool_allocated_bytes:
      default: false
      description: Total amount of memory allocated in pools (in bytes).
      type: gauge
    haproxy_process_pool_used_bytes:
      default: false
      description: Total amount of memory used in pools (in bytes).
      type: gauge
    haproxy_process_pool_failures:
      default: false
      description: Total number of failed pool allocations.
      type: cumulative
    haproxy_process_max_fds:
      default: false
      description: Maximum number of open file descriptors; 0=unset.
      type: gauge
    haproxy_process_max_sockets:
      default: false
      description: Maximum numer of open sockets.
      type: gauge
    haproxy_process_max_connections:
      default: false
      description: Maximum number of concurrent connections.
      type: gauge
    haproxy_process_hard_max_connections:
      default: false
      description: Initial Maximum number of concurrent connections.
      type: gauge
    haproxy_process_current_connections:
      default: false
      description: Number of active sessions.
      type: gauge
    haproxy_process_connections:
      default: false
      description: Total number of created sessions.
      type: cumulative
    haproxy_process_requests:
      default: false
      description: Total number of requests (TCP or HTTP).
      type: cumulative
    haproxy_process_max_ssl_connections:
      default: false
      description: Configured maximum number of concurrent SSL connections.
      type: gauge
    haproxy_process_current_ssl_connections:
      default: false
      description: Number of opened SSL connections.
      type: gauge
    haproxy_process_ssl_connections:
      default: false
      description: Total number of opened SSL connections.
      type: cumulative
    haproxy_process_max_pipes:
      default: false
      description: Configured maximum number of pipes.
      type: gauge
    haproxy_process_pipes_used:
      default: false
      description: Number of pipes in used.
      type: cumulative
    haproxy_process_pipes_free:
      default: false
      description: Number of pipes unused.
      type: cumulative
    haproxy_process_current_connection_rate:
      default: false
      description: Current number of connections per second over last elapsed second.
      type: gauge
    haproxy_process_limit_connection_rate:
      default: false
      description: Configured maximum number of connections per second.
      type: gauge
    haproxy_process_max_connection_rate:
      default: false
      description: Maximum observed number of connections per second.
      type: gauge
    haproxy_process_current_session_rate:
      default: false
      description: Current number of sessions per second over last elapsed second.
      type: gauge
    haproxy_process_limit_session_rate:
      default: false
      description: Configured maximum number of sessions per second.
      type: gauge
    haproxy_process_max_session_rate:
      default: false
      description: Maximum observed number of sessions per second.
      type: gauge
    haproxy_process_current_ssl_rate:
      default: false
      description: Current number of SSL sessions per second over last elapsed second.
      type: gauge
    haproxy_process_limit_ssl_rate:
      default: false
      description: Configured maximum number of SSL sessions per second.
      type: gauge
    haproxy_process_max_ssl_rate:
      default: false
      description: Maximum observed number of SSL sessions per second.
      type: gauge
    haproxy_process_current_frontend_ssl_key_rate:
      default: false
      description: Current frontend SSL Key computation per second over last elapsed
        second.
      type: gauge
    haproxy_process_max_frontend_ssl_key_rate:
      default: false
      description: Maximum observed frontend SSL Key computation per second.
      type: gauge
    haproxy_process_frontent_ssl_reuse:
      default: false
      description: SSL session reuse ratio (percent).
      type: gauge
    haproxy_process_current_backend_ssl_key_rate:
      default: false
      description: Current backend SSL Key computation per second over last elapsed
        second.
      type: gauge
    haproxy_process_max_backend_ssl_key_rate:
      default: false
      description: Maximum observed backend SSL Key computation per second.
      type: gauge
    haproxy_process_ssl_cache_lookups:
      default: false
      description: Total number of SSL session cache lookups.
      type: cumulative
    haproxy_process_ssl_cache_misses:
      default: false
      description: Total number of SSL session cache misses.
      type: cumulative
    haproxy_process_http_comp_bytes_in:
      default: false
      description: Number of bytes per second over last elapsed second, before http
        compression.
      type: cumulative
    haproxy_process_http_comp_bytes_out:
      default: false
      description: Number of bytes per second over last elapsed second, after http
        compression.
      type: cumulative
    haproxy_process_limit_http_comp:
      default: false
      description: Configured maximum input compression rate in bytes.
      type: gauge
    haproxy_process_current_zlib_memory:
      default: false
      description: Current memory used for zlib in bytes.
      type: gauge
    haproxy_process_max_zlib_memory:
      default: false
      description: Configured maximum amount of memory for zlib in bytes.
      type: gauge
    haproxy_process_current_tasks:
      default: false
      description: Current number of tasks.
      type: gauge
    haproxy_process_current_run_queue:
      default: false
      description: Current number of tasks in the run-queue.
      type: gauge
    haproxy_process_idle_time_percent:
      default: false
      description: Idle to total ratio over last sample (percent).
      type: gauge
    haproxy_process_stopping:
      default: false
      description: Non zero means stopping in progress.
      type: gauge
    haproxy_process_jobs:
      default: false
      description: Current number of active jobs (listeners, sessions, open devices).
      type: gauge
    haproxy_process_unstoppable_jobs:
      default: false
      description: Current number of active jobs that can't be stopped during a soft
        stop.
      type: gauge
    haproxy_process_listeners:
      default: false
      description: Current number of active listeners.
      type: gauge
    haproxy_process_active_peers:
      default: false
      description: Current number of active peers.
      type: gauge
    haproxy_process_connected_peers:
      default: false
      description: Current number of connected peers.
      type: gauge
    haproxy_process_dropped_logs:
      default: false
      description: Total number of dropped logs.
      type: cumulative
    haproxy_process_busy_polling_enabled:
      default: false
      description: Non zero if the busy polling is enabled.
      type: gauge
    haproxy_frontend_status:
      default: false
      description: 'Current status of the service (frontend: 0=STOP, 1=UP, 2=FULL
        - backend/server: 0=DOWN, 1=UP).'
      type: gauge
    haproxy_frontend_current_sessions:
      default: false
      description: Current number of active sessions.
      type: gauge
    haproxy_frontend_max_sessions:
      default: false
      description: Maximum observed number of active sessions.
      type: gauge
    haproxy_frontend_limit_sessions:
      default: false
      description: Configured session limit.
      type: gauge
    haproxy_frontend_sessions:
      default: false
      description: Total number of sessions.
      type: cumulative
    haproxy_frontend_limit_session_rate:
      default: false
      description: Configured limit on new sessions per second.
      type: gauge
    haproxy_frontend_max_session_rate:
      default: false
      description: Maximum observed number of sessions per second.
      type: gauge
    haproxy_frontend_connections_rate_max:
      default: false
      description: Maximum observed number of connections per second.
      type: gauge
    haproxy_frontend_connections:
      default: false
      description: Total number of connections.
      type: cumulative
    haproxy_frontend_bytes_in:
      default: true
      description: Current total of incoming bytes.
      type: cumulative
    haproxy_frontend_bytes_out:
      default: true
      description: Current total of outgoing bytes.
      type: cumulative
    haproxy_frontend_requests_denied:
      default: true
      description: Total number of denied requests.
      type: cumulative
    haproxy_frontend_responses_denied:
      default: true
      description: Total number of denied responses.
      type: cumulative
    haproxy_frontend_request_errors:
      default: true
      description: Total number of request errors.
      type: cumulative
    haproxy_frontend_denied_connections:
      default: true
      description: Total number of requests denied by "tcp-request connection" rules.
      type: cumulative
    haproxy_frontend_denied_sessions:
      default: false
      description: Total number of requests denied by "tcp-request session" rules.
      type: cumulative
    haproxy_frontend_failed_header_rewriting:
      default: false
      description: Total number of failed header rewriting warnings.
      type: cumulative
    haproxy_frontend_http_requests_rate_max:
      default: false
      description: Maximum observed number of HTTP requests per second.
      type: gauge
    haproxy_frontend_http_requests:
      default: false
      description: Total number of HTTP requests received.
      type: cumulative
    haproxy_frontend_http_responses:
      default: false
      description: Total number of HTTP responses.
      type: cumulative
    haproxy_frontend_intercepted_requests:
      default: false
      description: Total number of intercepted HTTP requests.
      type: cumulative
    haproxy_frontend_http_cache_lookups:
      default: false
      description: Total number of HTTP cache lookups.
      type: cumulative
    haproxy_frontend_http_cache_hits:
      default: false
      description: Total number of HTTP cache hits.
      type: cumulative
    haproxy_frontend_http_comp_bytes_in:
      default: false
      description: Total number of HTTP response bytes fed to the compressor.
      type: cumulative
    haproxy_frontend_http_comp_bytes_out:
      default: false
      description: Total number of HTTP response bytes emitted by the compressor.
      type: cumulative
    haproxy_frontend_http_comp_bytes_bypassed:
      default: false
      description: Total number of bytes that bypassed the HTTP compressor (CPU/BW
        limit).
      type: cumulative
    haproxy_frontend_http_comp_responses:
      default: false
      description: Total number of HTTP responses that were compressed.
      type: cumulative
