// Code generated by monitor-code-gen. DO NOT EDIT.

package vsphere

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "vsphere"

const (
	groupCPU            = "cpu"
	groupDatastore      = "datastore"
	groupDisk           = "disk"
	groupHbr            = "hbr"
	groupMem            = "mem"
	groupNet            = "net"
	groupPower          = "power"
	groupRescpu         = "rescpu"
	groupStorageAdapter = "storage_adapter"
	groupStoragePath    = "storage_path"
	groupSys            = "sys"
	groupVirtualDisk    = "virtual_disk"
)

var groupSet = map[string]bool{
	groupCPU:            true,
	groupDatastore:      true,
	groupDisk:           true,
	groupHbr:            true,
	groupMem:            true,
	groupNet:            true,
	groupPower:          true,
	groupRescpu:         true,
	groupStorageAdapter: true,
	groupStoragePath:    true,
	groupSys:            true,
	groupVirtualDisk:    true,
}

const (
	vsphereCPUCoreUtilizationPercent                 = "vsphere.cpu_core_utilization_percent"
	vsphereCPUCostopMs                               = "vsphere.cpu_costop_ms"
	vsphereCPUDemandEntitlementRatioPercent          = "vsphere.cpu_demand_entitlement_ratio_percent"
	vsphereCPUDemandMhz                              = "vsphere.cpu_demand_mhz"
	vsphereCPUEntitlementMhz                         = "vsphere.cpu_entitlement_mhz"
	vsphereCPUIdleMs                                 = "vsphere.cpu_idle_ms"
	vsphereCPUMaxlimitedMs                           = "vsphere.cpu_maxlimited_ms"
	vsphereCPUOverlapMs                              = "vsphere.cpu_overlap_ms"
	vsphereCPUReadinessPercent                       = "vsphere.cpu_readiness_percent"
	vsphereCPUReadyMs                                = "vsphere.cpu_ready_ms"
	vsphereCPUReservedCapacityMhz                    = "vsphere.cpu_reservedCapacity_mhz"
	vsphereCPURunMs                                  = "vsphere.cpu_run_ms"
	vsphereCPUSwapwaitMs                             = "vsphere.cpu_swapwait_ms"
	vsphereCPUSystemMs                               = "vsphere.cpu_system_ms"
	vsphereCPUTotalCapacityMhz                       = "vsphere.cpu_totalCapacity_mhz"
	vsphereCPUUsagePercent                           = "vsphere.cpu_usage_percent"
	vsphereCPUUsagemhz                               = "vsphere.cpu_usagemhz"
	vsphereCPUUsedPercent                            = "vsphere.cpu_used_percent"
	vsphereCPUUtilizationPercent                     = "vsphere.cpu_utilization_percent"
	vsphereCPUWaitMs                                 = "vsphere.cpu_wait_ms"
	vsphereDatastoreDatastoreReadLoadMetric          = "vsphere.datastore.datastore_read_load_metric"
	vsphereDatastoreDatastoreVmobservedLatencyMs     = "vsphere.datastore.datastore_vmobserved_latency_ms"
	vsphereDatastoreDatastoreWriteLoadMetric         = "vsphere.datastore.datastore_write_load_metric"
	vsphereDatastoreMaxTotalLatencyMs                = "vsphere.datastore.max_total_latency_ms"
	vsphereDatastoreReadKbs                          = "vsphere.datastore.read_kbs"
	vsphereDatastoreSizeNormalizedDatastoreLatencyMs = "vsphere.datastore.size_normalized_datastore_latency_ms"
	vsphereDatastoreTotalReadLatencyMs               = "vsphere.datastore.total_read_latency_ms"
	vsphereDatastoreTotalWriteLatencyMs              = "vsphere.datastore.total_write_latency_ms"
	vsphereDatastoreWriteKbs                         = "vsphere.datastore.write_kbs"
	vsphereDatastoreDatastoreIops                    = "vsphere.datastore_datastoreIops"
	vsphereDiskBusResets                             = "vsphere.disk.bus_resets"
	vsphereDiskCommands                              = "vsphere.disk.commands"
	vsphereDiskCommandsAborted                       = "vsphere.disk.commands_aborted"
	vsphereDiskCommandsAveraged                      = "vsphere.disk.commands_averaged"
	vsphereDiskDeviceLatencyMs                       = "vsphere.disk.device_latency_ms"
	vsphereDiskDeviceReadLatencyMs                   = "vsphere.disk.device_read_latency_ms"
	vsphereDiskDeviceWriteLatencyMs                  = "vsphere.disk.device_write_latency_ms"
	vsphereDiskKernelLatencyMs                       = "vsphere.disk.kernel_latency_ms"
	vsphereDiskKernelReadLatencyMs                   = "vsphere.disk.kernel_read_latency_ms"
	vsphereDiskKernelWriteLatencyMs                  = "vsphere.disk.kernel_write_latency_ms"
	vsphereDiskMaxQueueDepth                         = "vsphere.disk.max_queue_depth"
	vsphereDiskMaxTotalLatencyMs                     = "vsphere.disk.max_total_latency_ms"
	vsphereDiskNumberRead                            = "vsphere.disk.number_read"
	vsphereDiskNumberReadAveraged                    = "vsphere.disk.number_read_averaged"
	vsphereDiskNumberWrite                           = "vsphere.disk.number_write"
	vsphereDiskNumberWriteAveraged                   = "vsphere.disk.number_write_averaged"
	vsphereDiskQueueLatencyMs                        = "vsphere.disk.queue_latency_ms"
	vsphereDiskQueueReadLatencyMs                    = "vsphere.disk.queue_read_latency_ms"
	vsphereDiskQueueWriteLatencyMs                   = "vsphere.disk.queue_write_latency_ms"
	vsphereDiskReadKbs                               = "vsphere.disk.read_kbs"
	vsphereDiskTotalLatencyMs                        = "vsphere.disk.total_latency_ms"
	vsphereDiskTotalReadLatencyMs                    = "vsphere.disk.total_read_latency_ms"
	vsphereDiskTotalWriteLatencyMs                   = "vsphere.disk.total_write_latency_ms"
	vsphereDiskUsageKbs                              = "vsphere.disk.usage_kbs"
	vsphereDiskWriteKbs                              = "vsphere.disk.write_kbs"
	vsphereHbrHbrNetRxKbs                            = "vsphere.hbr.hbr_net_rx_kbs"
	vsphereHbrHbrNetTxKbs                            = "vsphere.hbr.hbr_net_tx_kbs"
	vsphereHbrHbrNumVms                              = "vsphere.hbr.hbr_num_vms"
	vsphereMemActiveKb                               = "vsphere.mem.active_kb"
	vsphereMemActivewriteKb                          = "vsphere.mem.activewrite_kb"
	vsphereMemCompressedKb                           = "vsphere.mem.compressed_kb"
	vsphereMemCompressionRateKbs                     = "vsphere.mem.compression_rate_kbs"
	vsphereMemConsumedKb                             = "vsphere.mem.consumed_kb"
	vsphereMemDecompressionRateKbs                   = "vsphere.mem.decompression_rate_kbs"
	vsphereMemEntitlementKb                          = "vsphere.mem.entitlement_kb"
	vsphereMemGrantedKb                              = "vsphere.mem.granted_kb"
	vsphereMemHeapKb                                 = "vsphere.mem.heap_kb"
	vsphereMemHeapfreeKb                             = "vsphere.mem.heapfree_kb"
	vsphereMemLatencyPercent                         = "vsphere.mem.latency_percent"
	vsphereMemLlSwapInKb                             = "vsphere.mem.ll_swap_in_kb"
	vsphereMemLlSwapInRateKbs                        = "vsphere.mem.ll_swap_in_rate_kbs"
	vsphereMemLlSwapOutKb                            = "vsphere.mem.ll_swap_out_kb"
	vsphereMemLlSwapOutRateKbs                       = "vsphere.mem.ll_swap_out_rate_kbs"
	vsphereMemLlSwapUsedKb                           = "vsphere.mem.ll_swap_used_kb"
	vsphereMemLowfreethresholdKb                     = "vsphere.mem.lowfreethreshold_kb"
	vsphereMemOverheadKb                             = "vsphere.mem.overhead_kb"
	vsphereMemOverheadMaxKb                          = "vsphere.mem.overhead_max_kb"
	vsphereMemOverheadTouchedKb                      = "vsphere.mem.overhead_touched_kb"
	vsphereMemReservedCapacityMb                     = "vsphere.mem.reserved_capacity_mb"
	vsphereMemSharedKb                               = "vsphere.mem.shared_kb"
	vsphereMemSharedcommonKb                         = "vsphere.mem.sharedcommon_kb"
	vsphereMemState                                  = "vsphere.mem.state"
	vsphereMemSwapinKb                               = "vsphere.mem.swapin_kb"
	vsphereMemSwapinRateKbs                          = "vsphere.mem.swapin_rate_kbs"
	vsphereMemSwapoutKb                              = "vsphere.mem.swapout_kb"
	vsphereMemSwapoutRateKbs                         = "vsphere.mem.swapout_rate_kbs"
	vsphereMemSwappedKb                              = "vsphere.mem.swapped_kb"
	vsphereMemSwaptargetKb                           = "vsphere.mem.swaptarget_kb"
	vsphereMemSwapusedKb                             = "vsphere.mem.swapused_kb"
	vsphereMemSysUsageKb                             = "vsphere.mem.sys_usage_kb"
	vsphereMemTotalCapacityMb                        = "vsphere.mem.total_capacity_mb"
	vsphereMemUnreservedKb                           = "vsphere.mem.unreserved_kb"
	vsphereMemUsagePercent                           = "vsphere.mem.usage_percent"
	vsphereMemVmfsPbcCapMissRatioPercent             = "vsphere.mem.vmfs_pbc_cap_miss_ratio_percent"
	vsphereMemVmfsPbcOverheadKb                      = "vsphere.mem.vmfs_pbc_overhead_kb"
	vsphereMemVmfsPbcSizeMaxMb                       = "vsphere.mem.vmfs_pbc_size_max_mb"
	vsphereMemVmfsPbcSizeMb                          = "vsphere.mem.vmfs_pbc_size_mb"
	vsphereMemVmfsPbcWorkingSetMaxTb                 = "vsphere.mem.vmfs_pbc_working_set_max_tb"
	vsphereMemVmfsPbcWorkingSetTb                    = "vsphere.mem.vmfs_pbc_working_set_tb"
	vsphereMemVmmemctlKb                             = "vsphere.mem.vmmemctl_kb"
	vsphereMemVmmemctltargetKb                       = "vsphere.mem.vmmemctltarget_kb"
	vsphereMemZeroKb                                 = "vsphere.mem.zero_kb"
	vsphereMemZipSavedKb                             = "vsphere.mem.zip_saved_kb"
	vsphereMemZippedKb                               = "vsphere.mem.zipped_kb"
	vsphereNetBroadcastRx                            = "vsphere.net.broadcast_rx"
	vsphereNetBroadcastTx                            = "vsphere.net.broadcast_tx"
	vsphereNetBytesRxKbs                             = "vsphere.net.bytes_rx_kbs"
	vsphereNetBytesTxKbs                             = "vsphere.net.bytes_tx_kbs"
	vsphereNetDroppedRx                              = "vsphere.net.dropped_rx"
	vsphereNetDroppedTx                              = "vsphere.net.dropped_tx"
	vsphereNetErrorsRx                               = "vsphere.net.errors_rx"
	vsphereNetErrorsTx                               = "vsphere.net.errors_tx"
	vsphereNetMulticastRx                            = "vsphere.net.multicast_rx"
	vsphereNetMulticastTx                            = "vsphere.net.multicast_tx"
	vsphereNetPacketsRx                              = "vsphere.net.packets_rx"
	vsphereNetPacketsTx                              = "vsphere.net.packets_tx"
	vsphereNetReceivedKbs                            = "vsphere.net.received_kbs"
	vsphereNetTransmittedKbs                         = "vsphere.net.transmitted_kbs"
	vsphereNetUnknownProtos                          = "vsphere.net.unknown_protos"
	vsphereNetUsageKbs                               = "vsphere.net.usage_kbs"
	vspherePowerEnergyJoules                         = "vsphere.power.energy_joules"
	vspherePowerPowerCapWatts                        = "vsphere.power.power_cap_watts"
	vspherePowerPowerWatts                           = "vsphere.power.power_watts"
	vsphereRescpuActav1                              = "vsphere.rescpu.actav1"
	vsphereRescpuActav15Percent                      = "vsphere.rescpu.actav15_percent"
	vsphereRescpuActav5Percent                       = "vsphere.rescpu.actav5_percent"
	vsphereRescpuActpk15Percent                      = "vsphere.rescpu.actpk15_percent"
	vsphereRescpuActpk1Percent                       = "vsphere.rescpu.actpk1_percent"
	vsphereRescpuActpk5Percent                       = "vsphere.rescpu.actpk5_percent"
	vsphereRescpuMaxLimited15Percent                 = "vsphere.rescpu.max_limited15_percent"
	vsphereRescpuMaxLimited1Percent                  = "vsphere.rescpu.max_limited1_percent"
	vsphereRescpuMaxLimited5Percent                  = "vsphere.rescpu.max_limited5_percent"
	vsphereRescpuRunav15Percent                      = "vsphere.rescpu.runav15_percent"
	vsphereRescpuRunav1Percent                       = "vsphere.rescpu.runav1_percent"
	vsphereRescpuRunav5Percent                       = "vsphere.rescpu.runav5_percent"
	vsphereRescpuRunpk15Percent                      = "vsphere.rescpu.runpk15_percent"
	vsphereRescpuRunpk1Percent                       = "vsphere.rescpu.runpk1_percent"
	vsphereRescpuRunpk5Percent                       = "vsphere.rescpu.runpk5_percent"
	vsphereRescpuSampleCount                         = "vsphere.rescpu.sample_count"
	vsphereRescpuSamplePeriodMs                      = "vsphere.rescpu.sample_period_ms"
	vsphereStorageAdapterCommandsAveraged            = "vsphere.storage_adapter.commands_averaged"
	vsphereStorageAdapterMaxTotalLatencyMs           = "vsphere.storage_adapter.max_total_latency_ms"
	vsphereStorageAdapterNumberReadAveraged          = "vsphere.storage_adapter.number_read_averaged"
	vsphereStorageAdapterNumberWriteAveraged         = "vsphere.storage_adapter.number_write_averaged"
	vsphereStorageAdapterReadKbs                     = "vsphere.storage_adapter.read_kbs"
	vsphereStorageAdapterTotalReadLatencyMs          = "vsphere.storage_adapter.total_read_latency_ms"
	vsphereStorageAdapterTotalWriteLatencyMs         = "vsphere.storage_adapter.total_write_latency_ms"
	vsphereStorageAdapterWriteKbs                    = "vsphere.storage_adapter.write_kbs"
	vsphereStoragePathCommandsAveraged               = "vsphere.storage_path.commands_averaged"
	vsphereStoragePathMaxTotalLatencyMs              = "vsphere.storage_path.max_total_latency_ms"
	vsphereStoragePathNumberReadAveraged             = "vsphere.storage_path.number_read_averaged"
	vsphereStoragePathNumberWriteAveraged            = "vsphere.storage_path.number_write_averaged"
	vsphereStoragePathReadKbs                        = "vsphere.storage_path.read_kbs"
	vsphereStoragePathTotalReadLatencyMs             = "vsphere.storage_path.total_read_latency_ms"
	vsphereStoragePathTotalWriteLatencyMs            = "vsphere.storage_path.total_write_latency_ms"
	vsphereStoragePathWriteKbs                       = "vsphere.storage_path.write_kbs"
	vsphereSysHeartbeat                              = "vsphere.sys.heartbeat"
	vsphereSysOsUptimeSeconds                        = "vsphere.sys.os_uptime_seconds"
	vsphereSysResourceCPUAct1Percent                 = "vsphere.sys.resource_cpu_act1_percent"
	vsphereSysResourceCPUAct5                        = "vsphere.sys.resource_cpu_act5"
	vsphereSysResourceCPUAllocMinMhz                 = "vsphere.sys.resource_cpu_alloc_min_mhz"
	vsphereSysResourceCPUAllocShares                 = "vsphere.sys.resource_cpu_alloc_shares"
	vsphereSysResourceCPUMaxLimited1Percent          = "vsphere.sys.resource_cpu_max_limited1_percent"
	vsphereSysResourceCPUMaxLimited5Percent          = "vsphere.sys.resource_cpu_max_limited5_percent"
	vsphereSysResourceCPURun1Percent                 = "vsphere.sys.resource_cpu_run1_percent"
	vsphereSysResourceCPURun5Percent                 = "vsphere.sys.resource_cpu_run5_percent"
	vsphereSysResourceCPUUsageMhz                    = "vsphere.sys.resource_cpu_usage_mhz"
	vsphereSysResourceFdUsage                        = "vsphere.sys.resource_fd_usage"
	vsphereSysResourceMemAllocMaxKb                  = "vsphere.sys.resource_mem_alloc_max_kb"
	vsphereSysResourceMemAllocMinKb                  = "vsphere.sys.resource_mem_alloc_min_kb"
	vsphereSysResourceMemAllocShares                 = "vsphere.sys.resource_mem_alloc_shares"
	vsphereSysResourceMemConsumedKb                  = "vsphere.sys.resource_mem_consumed_kb"
	vsphereSysResourceMemCowKb                       = "vsphere.sys.resource_mem_cow_kb"
	vsphereSysResourceMemMappedKb                    = "vsphere.sys.resource_mem_mapped_kb"
	vsphereSysResourceMemOverheadKb                  = "vsphere.sys.resource_mem_overhead_kb"
	vsphereSysResourceMemSharedKb                    = "vsphere.sys.resource_mem_shared_kb"
	vsphereSysResourceMemSwappedKb                   = "vsphere.sys.resource_mem_swapped_kb"
	vsphereSysResourceMemTouchedKb                   = "vsphere.sys.resource_mem_touched_kb"
	vsphereSysResourceMemZeroKb                      = "vsphere.sys.resource_mem_zero_kb"
	vsphereSysUptimeSeconds                          = "vsphere.sys.uptime_seconds"
	vsphereVirtualDiskLargeSeeks                     = "vsphere.virtual_disk.large_seeks"
	vsphereVirtualDiskMediumSeeks                    = "vsphere.virtual_disk.medium_seeks"
	vsphereVirtualDiskNumberReadAveraged             = "vsphere.virtual_disk.number_read_averaged"
	vsphereVirtualDiskNumberWriteAveraged            = "vsphere.virtual_disk.number_write_averaged"
	vsphereVirtualDiskReadIosize                     = "vsphere.virtual_disk.read_iosize"
	vsphereVirtualDiskReadKbs                        = "vsphere.virtual_disk.read_kbs"
	vsphereVirtualDiskReadLatencyUs                  = "vsphere.virtual_disk.read_latency_us"
	vsphereVirtualDiskReadLoadMetric                 = "vsphere.virtual_disk.read_load_metric"
	vsphereVirtualDiskReadOio                        = "vsphere.virtual_disk.read_oio"
	vsphereVirtualDiskSmallSeeks                     = "vsphere.virtual_disk.small_seeks"
	vsphereVirtualDiskTotalReadLatencyMs             = "vsphere.virtual_disk.total_read_latency_ms"
	vsphereVirtualDiskTotalWriteLatencyMs            = "vsphere.virtual_disk.total_write_latency_ms"
	vsphereVirtualDiskWriteIosize                    = "vsphere.virtual_disk.write_iosize"
	vsphereVirtualDiskWriteKbs                       = "vsphere.virtual_disk.write_kbs"
	vsphereVirtualDiskWriteLatencyUs                 = "vsphere.virtual_disk.write_latency_us"
	vsphereVirtualDiskWriteLoadMetric                = "vsphere.virtual_disk.write_load_metric"
	vsphereVirtualDiskWriteOio                       = "vsphere.virtual_disk.write_oio"
	vsphereCPULatencyPercent                         = "vsphere_cpu_latency_percent"
)

var metricSet = map[string]monitors.MetricInfo{
	vsphereCPUCoreUtilizationPercent:                 {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPUCostopMs:                               {Type: datapoint.Count, Group: groupCPU},
	vsphereCPUDemandEntitlementRatioPercent:          {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPUDemandMhz:                              {Type: datapoint.Count, Group: groupCPU},
	vsphereCPUEntitlementMhz:                         {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPUIdleMs:                                 {Type: datapoint.Count, Group: groupCPU},
	vsphereCPUMaxlimitedMs:                           {Type: datapoint.Count, Group: groupCPU},
	vsphereCPUOverlapMs:                              {Type: datapoint.Count, Group: groupCPU},
	vsphereCPUReadinessPercent:                       {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPUReadyMs:                                {Type: datapoint.Count, Group: groupCPU},
	vsphereCPUReservedCapacityMhz:                    {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPURunMs:                                  {Type: datapoint.Count, Group: groupCPU},
	vsphereCPUSwapwaitMs:                             {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPUSystemMs:                               {Type: datapoint.Count, Group: groupCPU},
	vsphereCPUTotalCapacityMhz:                       {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPUUsagePercent:                           {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPUUsagemhz:                               {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPUUsedPercent:                            {Type: datapoint.Count, Group: groupCPU},
	vsphereCPUUtilizationPercent:                     {Type: datapoint.Gauge, Group: groupCPU},
	vsphereCPUWaitMs:                                 {Type: datapoint.Count, Group: groupCPU},
	vsphereDatastoreDatastoreReadLoadMetric:          {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDatastoreDatastoreVmobservedLatencyMs:     {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDatastoreDatastoreWriteLoadMetric:         {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDatastoreMaxTotalLatencyMs:                {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDatastoreReadKbs:                          {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDatastoreSizeNormalizedDatastoreLatencyMs: {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDatastoreTotalReadLatencyMs:               {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDatastoreTotalWriteLatencyMs:              {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDatastoreWriteKbs:                         {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDatastoreDatastoreIops:                    {Type: datapoint.Gauge, Group: groupDatastore},
	vsphereDiskBusResets:                             {Type: datapoint.Count, Group: groupDisk},
	vsphereDiskCommands:                              {Type: datapoint.Count, Group: groupDisk},
	vsphereDiskCommandsAborted:                       {Type: datapoint.Count, Group: groupDisk},
	vsphereDiskCommandsAveraged:                      {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskDeviceLatencyMs:                       {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskDeviceReadLatencyMs:                   {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskDeviceWriteLatencyMs:                  {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskKernelLatencyMs:                       {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskKernelReadLatencyMs:                   {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskKernelWriteLatencyMs:                  {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskMaxQueueDepth:                         {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskMaxTotalLatencyMs:                     {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskNumberRead:                            {Type: datapoint.Count, Group: groupDisk},
	vsphereDiskNumberReadAveraged:                    {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskNumberWrite:                           {Type: datapoint.Count, Group: groupDisk},
	vsphereDiskNumberWriteAveraged:                   {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskQueueLatencyMs:                        {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskQueueReadLatencyMs:                    {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskQueueWriteLatencyMs:                   {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskReadKbs:                               {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskTotalLatencyMs:                        {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskTotalReadLatencyMs:                    {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskTotalWriteLatencyMs:                   {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskUsageKbs:                              {Type: datapoint.Gauge, Group: groupDisk},
	vsphereDiskWriteKbs:                              {Type: datapoint.Gauge, Group: groupDisk},
	vsphereHbrHbrNetRxKbs:                            {Type: datapoint.Gauge, Group: groupHbr},
	vsphereHbrHbrNetTxKbs:                            {Type: datapoint.Gauge, Group: groupHbr},
	vsphereHbrHbrNumVms:                              {Type: datapoint.Gauge, Group: groupHbr},
	vsphereMemActiveKb:                               {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemActivewriteKb:                          {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemCompressedKb:                           {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemCompressionRateKbs:                     {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemConsumedKb:                             {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemDecompressionRateKbs:                   {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemEntitlementKb:                          {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemGrantedKb:                              {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemHeapKb:                                 {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemHeapfreeKb:                             {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemLatencyPercent:                         {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemLlSwapInKb:                             {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemLlSwapInRateKbs:                        {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemLlSwapOutKb:                            {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemLlSwapOutRateKbs:                       {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemLlSwapUsedKb:                           {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemLowfreethresholdKb:                     {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemOverheadKb:                             {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemOverheadMaxKb:                          {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemOverheadTouchedKb:                      {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemReservedCapacityMb:                     {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSharedKb:                               {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSharedcommonKb:                         {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemState:                                  {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSwapinKb:                               {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSwapinRateKbs:                          {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSwapoutKb:                              {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSwapoutRateKbs:                         {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSwappedKb:                              {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSwaptargetKb:                           {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSwapusedKb:                             {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemSysUsageKb:                             {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemTotalCapacityMb:                        {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemUnreservedKb:                           {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemUsagePercent:                           {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemVmfsPbcCapMissRatioPercent:             {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemVmfsPbcOverheadKb:                      {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemVmfsPbcSizeMaxMb:                       {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemVmfsPbcSizeMb:                          {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemVmfsPbcWorkingSetMaxTb:                 {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemVmfsPbcWorkingSetTb:                    {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemVmmemctlKb:                             {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemVmmemctltargetKb:                       {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemZeroKb:                                 {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemZipSavedKb:                             {Type: datapoint.Gauge, Group: groupMem},
	vsphereMemZippedKb:                               {Type: datapoint.Gauge, Group: groupMem},
	vsphereNetBroadcastRx:                            {Type: datapoint.Count, Group: groupNet},
	vsphereNetBroadcastTx:                            {Type: datapoint.Count, Group: groupNet},
	vsphereNetBytesRxKbs:                             {Type: datapoint.Gauge, Group: groupNet},
	vsphereNetBytesTxKbs:                             {Type: datapoint.Gauge, Group: groupNet},
	vsphereNetDroppedRx:                              {Type: datapoint.Count, Group: groupNet},
	vsphereNetDroppedTx:                              {Type: datapoint.Count, Group: groupNet},
	vsphereNetErrorsRx:                               {Type: datapoint.Count, Group: groupNet},
	vsphereNetErrorsTx:                               {Type: datapoint.Count, Group: groupNet},
	vsphereNetMulticastRx:                            {Type: datapoint.Count, Group: groupNet},
	vsphereNetMulticastTx:                            {Type: datapoint.Count, Group: groupNet},
	vsphereNetPacketsRx:                              {Type: datapoint.Count, Group: groupNet},
	vsphereNetPacketsTx:                              {Type: datapoint.Count, Group: groupNet},
	vsphereNetReceivedKbs:                            {Type: datapoint.Gauge, Group: groupNet},
	vsphereNetTransmittedKbs:                         {Type: datapoint.Gauge, Group: groupNet},
	vsphereNetUnknownProtos:                          {Type: datapoint.Count, Group: groupNet},
	vsphereNetUsageKbs:                               {Type: datapoint.Gauge, Group: groupNet},
	vspherePowerEnergyJoules:                         {Type: datapoint.Count, Group: groupPower},
	vspherePowerPowerCapWatts:                        {Type: datapoint.Gauge, Group: groupPower},
	vspherePowerPowerWatts:                           {Type: datapoint.Gauge, Group: groupPower},
	vsphereRescpuActav1:                              {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuActav15Percent:                      {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuActav5Percent:                       {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuActpk15Percent:                      {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuActpk1Percent:                       {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuActpk5Percent:                       {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuMaxLimited15Percent:                 {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuMaxLimited1Percent:                  {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuMaxLimited5Percent:                  {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuRunav15Percent:                      {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuRunav1Percent:                       {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuRunav5Percent:                       {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuRunpk15Percent:                      {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuRunpk1Percent:                       {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuRunpk5Percent:                       {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuSampleCount:                         {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereRescpuSamplePeriodMs:                      {Type: datapoint.Gauge, Group: groupRescpu},
	vsphereStorageAdapterCommandsAveraged:            {Type: datapoint.Gauge, Group: groupStorageAdapter},
	vsphereStorageAdapterMaxTotalLatencyMs:           {Type: datapoint.Gauge, Group: groupStorageAdapter},
	vsphereStorageAdapterNumberReadAveraged:          {Type: datapoint.Gauge, Group: groupStorageAdapter},
	vsphereStorageAdapterNumberWriteAveraged:         {Type: datapoint.Gauge, Group: groupStorageAdapter},
	vsphereStorageAdapterReadKbs:                     {Type: datapoint.Gauge, Group: groupStorageAdapter},
	vsphereStorageAdapterTotalReadLatencyMs:          {Type: datapoint.Gauge, Group: groupStorageAdapter},
	vsphereStorageAdapterTotalWriteLatencyMs:         {Type: datapoint.Gauge, Group: groupStorageAdapter},
	vsphereStorageAdapterWriteKbs:                    {Type: datapoint.Gauge, Group: groupStorageAdapter},
	vsphereStoragePathCommandsAveraged:               {Type: datapoint.Gauge, Group: groupStoragePath},
	vsphereStoragePathMaxTotalLatencyMs:              {Type: datapoint.Gauge, Group: groupStoragePath},
	vsphereStoragePathNumberReadAveraged:             {Type: datapoint.Gauge, Group: groupStoragePath},
	vsphereStoragePathNumberWriteAveraged:            {Type: datapoint.Gauge, Group: groupStoragePath},
	vsphereStoragePathReadKbs:                        {Type: datapoint.Gauge, Group: groupStoragePath},
	vsphereStoragePathTotalReadLatencyMs:             {Type: datapoint.Gauge, Group: groupStoragePath},
	vsphereStoragePathTotalWriteLatencyMs:            {Type: datapoint.Gauge, Group: groupStoragePath},
	vsphereStoragePathWriteKbs:                       {Type: datapoint.Gauge, Group: groupStoragePath},
	vsphereSysHeartbeat:                              {Type: datapoint.Count, Group: groupSys},
	vsphereSysOsUptimeSeconds:                        {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceCPUAct1Percent:                 {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceCPUAct5:                        {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceCPUAllocMinMhz:                 {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceCPUAllocShares:                 {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceCPUMaxLimited1Percent:          {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceCPUMaxLimited5Percent:          {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceCPURun1Percent:                 {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceCPURun5Percent:                 {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceCPUUsageMhz:                    {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceFdUsage:                        {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemAllocMaxKb:                  {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemAllocMinKb:                  {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemAllocShares:                 {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemConsumedKb:                  {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemCowKb:                       {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemMappedKb:                    {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemOverheadKb:                  {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemSharedKb:                    {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemSwappedKb:                   {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemTouchedKb:                   {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysResourceMemZeroKb:                      {Type: datapoint.Gauge, Group: groupSys},
	vsphereSysUptimeSeconds:                          {Type: datapoint.Gauge, Group: groupSys},
	vsphereVirtualDiskLargeSeeks:                     {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskMediumSeeks:                    {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskNumberReadAveraged:             {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskNumberWriteAveraged:            {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskReadIosize:                     {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskReadKbs:                        {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskReadLatencyUs:                  {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskReadLoadMetric:                 {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskReadOio:                        {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskSmallSeeks:                     {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskTotalReadLatencyMs:             {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskTotalWriteLatencyMs:            {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskWriteIosize:                    {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskWriteKbs:                       {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskWriteLatencyUs:                 {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskWriteLoadMetric:                {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereVirtualDiskWriteOio:                       {Type: datapoint.Gauge, Group: groupVirtualDisk},
	vsphereCPULatencyPercent:                         {Type: datapoint.Gauge, Group: groupCPU},
}

var defaultMetrics = map[string]bool{}

var groupMetricsMap = map[string][]string{
	groupCPU: []string{
		vsphereCPUCoreUtilizationPercent,
		vsphereCPUCostopMs,
		vsphereCPUDemandEntitlementRatioPercent,
		vsphereCPUDemandMhz,
		vsphereCPUEntitlementMhz,
		vsphereCPUIdleMs,
		vsphereCPUMaxlimitedMs,
		vsphereCPUOverlapMs,
		vsphereCPUReadinessPercent,
		vsphereCPUReadyMs,
		vsphereCPUReservedCapacityMhz,
		vsphereCPURunMs,
		vsphereCPUSwapwaitMs,
		vsphereCPUSystemMs,
		vsphereCPUTotalCapacityMhz,
		vsphereCPUUsagePercent,
		vsphereCPUUsagemhz,
		vsphereCPUUsedPercent,
		vsphereCPUUtilizationPercent,
		vsphereCPUWaitMs,
		vsphereCPULatencyPercent,
	},
	groupDatastore: []string{
		vsphereDatastoreDatastoreReadLoadMetric,
		vsphereDatastoreDatastoreVmobservedLatencyMs,
		vsphereDatastoreDatastoreWriteLoadMetric,
		vsphereDatastoreMaxTotalLatencyMs,
		vsphereDatastoreReadKbs,
		vsphereDatastoreSizeNormalizedDatastoreLatencyMs,
		vsphereDatastoreTotalReadLatencyMs,
		vsphereDatastoreTotalWriteLatencyMs,
		vsphereDatastoreWriteKbs,
		vsphereDatastoreDatastoreIops,
	},
	groupDisk: []string{
		vsphereDiskBusResets,
		vsphereDiskCommands,
		vsphereDiskCommandsAborted,
		vsphereDiskCommandsAveraged,
		vsphereDiskDeviceLatencyMs,
		vsphereDiskDeviceReadLatencyMs,
		vsphereDiskDeviceWriteLatencyMs,
		vsphereDiskKernelLatencyMs,
		vsphereDiskKernelReadLatencyMs,
		vsphereDiskKernelWriteLatencyMs,
		vsphereDiskMaxQueueDepth,
		vsphereDiskMaxTotalLatencyMs,
		vsphereDiskNumberRead,
		vsphereDiskNumberReadAveraged,
		vsphereDiskNumberWrite,
		vsphereDiskNumberWriteAveraged,
		vsphereDiskQueueLatencyMs,
		vsphereDiskQueueReadLatencyMs,
		vsphereDiskQueueWriteLatencyMs,
		vsphereDiskReadKbs,
		vsphereDiskTotalLatencyMs,
		vsphereDiskTotalReadLatencyMs,
		vsphereDiskTotalWriteLatencyMs,
		vsphereDiskUsageKbs,
		vsphereDiskWriteKbs,
	},
	groupHbr: []string{
		vsphereHbrHbrNetRxKbs,
		vsphereHbrHbrNetTxKbs,
		vsphereHbrHbrNumVms,
	},
	groupMem: []string{
		vsphereMemActiveKb,
		vsphereMemActivewriteKb,
		vsphereMemCompressedKb,
		vsphereMemCompressionRateKbs,
		vsphereMemConsumedKb,
		vsphereMemDecompressionRateKbs,
		vsphereMemEntitlementKb,
		vsphereMemGrantedKb,
		vsphereMemHeapKb,
		vsphereMemHeapfreeKb,
		vsphereMemLatencyPercent,
		vsphereMemLlSwapInKb,
		vsphereMemLlSwapInRateKbs,
		vsphereMemLlSwapOutKb,
		vsphereMemLlSwapOutRateKbs,
		vsphereMemLlSwapUsedKb,
		vsphereMemLowfreethresholdKb,
		vsphereMemOverheadKb,
		vsphereMemOverheadMaxKb,
		vsphereMemOverheadTouchedKb,
		vsphereMemReservedCapacityMb,
		vsphereMemSharedKb,
		vsphereMemSharedcommonKb,
		vsphereMemState,
		vsphereMemSwapinKb,
		vsphereMemSwapinRateKbs,
		vsphereMemSwapoutKb,
		vsphereMemSwapoutRateKbs,
		vsphereMemSwappedKb,
		vsphereMemSwaptargetKb,
		vsphereMemSwapusedKb,
		vsphereMemSysUsageKb,
		vsphereMemTotalCapacityMb,
		vsphereMemUnreservedKb,
		vsphereMemUsagePercent,
		vsphereMemVmfsPbcCapMissRatioPercent,
		vsphereMemVmfsPbcOverheadKb,
		vsphereMemVmfsPbcSizeMaxMb,
		vsphereMemVmfsPbcSizeMb,
		vsphereMemVmfsPbcWorkingSetMaxTb,
		vsphereMemVmfsPbcWorkingSetTb,
		vsphereMemVmmemctlKb,
		vsphereMemVmmemctltargetKb,
		vsphereMemZeroKb,
		vsphereMemZipSavedKb,
		vsphereMemZippedKb,
	},
	groupNet: []string{
		vsphereNetBroadcastRx,
		vsphereNetBroadcastTx,
		vsphereNetBytesRxKbs,
		vsphereNetBytesTxKbs,
		vsphereNetDroppedRx,
		vsphereNetDroppedTx,
		vsphereNetErrorsRx,
		vsphereNetErrorsTx,
		vsphereNetMulticastRx,
		vsphereNetMulticastTx,
		vsphereNetPacketsRx,
		vsphereNetPacketsTx,
		vsphereNetReceivedKbs,
		vsphereNetTransmittedKbs,
		vsphereNetUnknownProtos,
		vsphereNetUsageKbs,
	},
	groupPower: []string{
		vspherePowerEnergyJoules,
		vspherePowerPowerCapWatts,
		vspherePowerPowerWatts,
	},
	groupRescpu: []string{
		vsphereRescpuActav1,
		vsphereRescpuActav15Percent,
		vsphereRescpuActav5Percent,
		vsphereRescpuActpk15Percent,
		vsphereRescpuActpk1Percent,
		vsphereRescpuActpk5Percent,
		vsphereRescpuMaxLimited15Percent,
		vsphereRescpuMaxLimited1Percent,
		vsphereRescpuMaxLimited5Percent,
		vsphereRescpuRunav15Percent,
		vsphereRescpuRunav1Percent,
		vsphereRescpuRunav5Percent,
		vsphereRescpuRunpk15Percent,
		vsphereRescpuRunpk1Percent,
		vsphereRescpuRunpk5Percent,
		vsphereRescpuSampleCount,
		vsphereRescpuSamplePeriodMs,
	},
	groupStorageAdapter: []string{
		vsphereStorageAdapterCommandsAveraged,
		vsphereStorageAdapterMaxTotalLatencyMs,
		vsphereStorageAdapterNumberReadAveraged,
		vsphereStorageAdapterNumberWriteAveraged,
		vsphereStorageAdapterReadKbs,
		vsphereStorageAdapterTotalReadLatencyMs,
		vsphereStorageAdapterTotalWriteLatencyMs,
		vsphereStorageAdapterWriteKbs,
	},
	groupStoragePath: []string{
		vsphereStoragePathCommandsAveraged,
		vsphereStoragePathMaxTotalLatencyMs,
		vsphereStoragePathNumberReadAveraged,
		vsphereStoragePathNumberWriteAveraged,
		vsphereStoragePathReadKbs,
		vsphereStoragePathTotalReadLatencyMs,
		vsphereStoragePathTotalWriteLatencyMs,
		vsphereStoragePathWriteKbs,
	},
	groupSys: []string{
		vsphereSysHeartbeat,
		vsphereSysOsUptimeSeconds,
		vsphereSysResourceCPUAct1Percent,
		vsphereSysResourceCPUAct5,
		vsphereSysResourceCPUAllocMinMhz,
		vsphereSysResourceCPUAllocShares,
		vsphereSysResourceCPUMaxLimited1Percent,
		vsphereSysResourceCPUMaxLimited5Percent,
		vsphereSysResourceCPURun1Percent,
		vsphereSysResourceCPURun5Percent,
		vsphereSysResourceCPUUsageMhz,
		vsphereSysResourceFdUsage,
		vsphereSysResourceMemAllocMaxKb,
		vsphereSysResourceMemAllocMinKb,
		vsphereSysResourceMemAllocShares,
		vsphereSysResourceMemConsumedKb,
		vsphereSysResourceMemCowKb,
		vsphereSysResourceMemMappedKb,
		vsphereSysResourceMemOverheadKb,
		vsphereSysResourceMemSharedKb,
		vsphereSysResourceMemSwappedKb,
		vsphereSysResourceMemTouchedKb,
		vsphereSysResourceMemZeroKb,
		vsphereSysUptimeSeconds,
	},
	groupVirtualDisk: []string{
		vsphereVirtualDiskLargeSeeks,
		vsphereVirtualDiskMediumSeeks,
		vsphereVirtualDiskNumberReadAveraged,
		vsphereVirtualDiskNumberWriteAveraged,
		vsphereVirtualDiskReadIosize,
		vsphereVirtualDiskReadKbs,
		vsphereVirtualDiskReadLatencyUs,
		vsphereVirtualDiskReadLoadMetric,
		vsphereVirtualDiskReadOio,
		vsphereVirtualDiskSmallSeeks,
		vsphereVirtualDiskTotalReadLatencyMs,
		vsphereVirtualDiskTotalWriteLatencyMs,
		vsphereVirtualDiskWriteIosize,
		vsphereVirtualDiskWriteKbs,
		vsphereVirtualDiskWriteLatencyUs,
		vsphereVirtualDiskWriteLoadMetric,
		vsphereVirtualDiskWriteOio,
	},
}

var monitorMetadata = monitors.Metadata{
	MonitorType:       "vsphere",
	DefaultMetrics:    defaultMetrics,
	Metrics:           metricSet,
	MetricsExhaustive: false,
	Groups:            groupSet,
	GroupMetricsMap:   groupMetricsMap,
	SendAll:           false,
}
