// +build linux

package statsd

//go:generate collectd-template-to-go statsd.tmpl

import (
	"github.com/signalfx/signalfx-agent/internal/core/config"
	"github.com/signalfx/signalfx-agent/internal/monitors"
	"github.com/signalfx/signalfx-agent/internal/monitors/collectd"
)

const monitorType = "collectd/statsd"

// MONITOR(collectd/statsd): The StatsD plugin for collectd listens for StatsD
// events, aggregates them and transmits them according to collectd's
// configuration. Use this plugin to send data from StatsD to SignalFx [statsd
// plugin](https://collectd.org/wiki/index.php/Plugin:StatsD).
//
// SignalFx supports `Counter`, `Timer` and `Gauge` types which are dispatched
// as the collectd types - `derive`, `latency` and `gauge` respectively.
// In SignalFx, for a statsd metric, its collectd type is attached as a
// prefix to the metric name. As an example, if you send in the gauge -
//
// ```
// $ echo "statsd.test:1|g" | nc -w 1 -u 127.0.0.1 8125
// ```
//
// This will be reported to SignalFx as "gauge.statsd.test"
//
// ### USAGE
//
// #### Adding dimensions to StatsD metrics
//
// Add dimensions to your metrics by adding key-value pairs to your StatsD
// metric names as follows:
//
// ```
// $ echo "statsd.[foo=bar,dim=val]test:1|g" | nc -w 1 -u 127.0.0.1 8125
// ```
//
// This creates a metric called `statsd.test` of type gauge, with dimensions
// `foo=bar` and `dim=val`.
//
// #### Delete[Type]s boolean setting
//
// These options control what happens if metrics are not updated in an
// interval. If set to False, the default, metrics are dispatched unchanged,
// i.e. the rate of counters and size of sets will be zero, timers report NaN
// and gauges are unchanged. If set to True, the such metrics are not
// dispatched and removed from the internal cache.
//
// SignalFx's default configuration for this plugin sets all `Delete[Type]s`
// configuration options to `True`. We strongly recommend this in order to
// ensure that metrics that have stopped reporting are not reported as 0 in
// perpetuity. Setting these parameters to `False` results in collectd's memory
// usage increasing over time, as the set of metrics reported from StatsD grows
// indefinitely. This is especially important in environments that are
// long-running or whose metrics change frequently.
//
// #### CounterSum boolean setting
//
// When enabled, creates a count metric which reports the change since the last
// read. This option primarily exists for compatibility with the statsd
// implementation by Etsy.
//
// If you are only looking at the counts generated by each reporting interval,
// equivalent to
// [Counters](https://docs.signalfx.com/en/latest/concepts/metric-types.html?highlight=Counters)
// in SignalFx then we'd recommend that you set CounterSum to `True`. It will
// send in an additional counter metric with a prefix of `count`.
//
//
// Sample YAML configuration:
//
// ```
// monitors:
//  - type: collectd/statsd
//    listenAddress: "0.0.0.0"
//    listenPort: 8125
//    deleteSets: true
//    timerPercentile: 90.0
// ```

func init() {
	monitors.Register(monitorType, func() interface{} {
		return &Monitor{
			*collectd.NewMonitorCore(CollectdTemplate),
		}
	}, &Config{})
}

// Config is the monitor-specific config with the generic config embedded
type Config struct {
	config.MonitorConfig `singleInstance:"true"`

	// The host/address on which to bind the UDP listener that accepts statsd
	// datagrams
	ListenAddress string `yaml:"listenAddress" default:"localhost"`
	// The port on which to listen for statsd messages
	ListenPort      uint16  `yaml:"listenPort" default:"8125"`
	DeleteSets      bool    `yaml:"deleteSets"`
	DeleteCounters  bool    `yaml:"deleteCounters"`
	DeleteTimers    bool    `yaml:"deleteTimers"`
	DeleteGauges    bool    `yaml:"deleteGauges"`
	TimerPercentile float64 `yaml:"timerPercentile"`
	TimerUpper      bool    `yaml:"timerUpper"`
	TimerSum        bool    `yaml:"timerSum"`
	TimerLower      bool    `yaml:"timerLower"`
	CounterSum      bool    `yaml:"counterSum"`
}

// Monitor is the main type that represents the monitor
type Monitor struct {
	collectd.MonitorCore
}

// Configure configures and runs the plugin in collectd
func (am *Monitor) Configure(conf *Config) error {
	return am.SetConfigurationAndRun(conf)
}
