#!/bin/bash

set -euxo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

AGENT_CHART_DIR="$SCRIPT_DIR/helm/signalfx-agent"

AGENT_VERSION=${AGENT_VERSION-$($SCRIPT_DIR/../../scripts/latest-final-release)}

templates="configmap.yaml daemonset.yaml clusterrole.yaml clusterrolebinding.yaml serviceaccount.yaml"
for f in $templates; do
  helm template \
    --namespace signalfx-agent \
    --set signalFxAccessToken=MY_TOKEN \
    --set clusterName=MY-CLUSTER \
    --set fullnameOverride=signalfx-agent \
    --set agentVersion=$AGENT_VERSION \
    -x ${AGENT_CHART_DIR%/}/templates/$f \
    $AGENT_CHART_DIR | \
      sed -e 's/[[:space:]]*$//' | \
      sed -e 's@apiVersion: apps/v1beta2@apiVersion: extensions/v1beta1@' | \
      grep -v 'chart: signalfx-agent' | \
      grep -v 'namespace: signalfx-agent' | \
      grep -v 'heritage: Tiller' | \
      grep -iv 'release: RELEASE-NAME' \
    > $SCRIPT_DIR/$f
  echo "Wrote resource $f"
done

echo '  namespace: MY_AGENT_NAMESPACE' >> $SCRIPT_DIR/clusterrolebinding.yaml
