---
# Source: signalfx-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: signalfx-agent
    heritage: Tiller
    release: release-name
  name: signalfx-agent
