FROM centos:6

# Centos 6 is EOL; update yum repo for vault
RUN sed -i '/^mirrorlist.*/d' /etc/yum.repos.d/CentOS-Base.repo
RUN sed -i 's|^#baseurl=http://mirror.centos.org/\(.*\)|baseurl=http://vault.centos.org/\1|' /etc/yum.repos.d/CentOS-Base.repo

RUN yum install -y upstart procps udev initscripts

ARG PUPPET_RELEASE=""
RUN rpm -Uvh https://yum.puppet.com/puppet${PUPPET_RELEASE}-release-el-6.noarch.rpm && \
    yum install -y puppet-agent

COPY tests/packaging/images/init-fake.conf /etc/init/fake-container-events.conf
COPY deployments/puppet /etc/puppetlabs/code/environments/production/modules/signalfx_agent

ENV PATH=/opt/puppetlabs/bin:$PATH

CMD ["/sbin/init", "-v"]
