// Code generated by monitor-code-gen. DO NOT EDIT.

package mongodbatlas

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "mongodbatlas"

const (
	groupWiredTiger      = "WiredTiger"
	groupHardwaremetrics = "hardwaremetrics"
	groupMongodbmetrics  = "mongodbmetrics"
)

var groupSet = map[string]bool{
	groupWiredTiger:      true,
	groupHardwaremetrics: true,
	groupMongodbmetrics:  true,
}

const (
	assertsMsg                              = "asserts.msg"
	assertsRegular                          = "asserts.regular"
	assertsUser                             = "asserts.user"
	assertsWarning                          = "asserts.warning"
	cacheBytesReadInto                      = "cache.bytes.readInto"
	cacheBytesWrittenFrom                   = "cache.bytes.writtenFrom"
	cacheDirtyBytes                         = "cache.dirtyBytes"
	cacheUsedBytes                          = "cache.usedBytes"
	connectionsCurrent                      = "connections.current"
	cursorsTimedOut                         = "cursors.timedOut"
	cursorsTotalOpen                        = "cursors.totalOpen"
	dataSize                                = "dataSize"
	diskPartitionIopsRead                   = "disk.partition.iops.read"
	diskPartitionIopsTotal                  = "disk.partition.iops.total"
	diskPartitionIopsWrite                  = "disk.partition.iops.write"
	diskPartitionLatencyRead                = "disk.partition.latency.read"
	diskPartitionLatencyWrite               = "disk.partition.latency.write"
	diskPartitionSpaceFree                  = "disk.partition.space.free"
	diskPartitionSpacePercentFree           = "disk.partition.space.percentFree"
	diskPartitionSpacePercentUsed           = "disk.partition.space.percentUsed"
	diskPartitionSpaceUsed                  = "disk.partition.space.used"
	diskPartitionUtilization                = "disk.partition.utilization"
	documentMetricsDeleted                  = "document.metrics.deleted"
	documentMetricsInserted                 = "document.metrics.inserted"
	documentMetricsReturned                 = "document.metrics.returned"
	documentMetricsUpdated                  = "document.metrics.updated"
	globalLockCurrentQueueReaders           = "globalLock.currentQueue.readers"
	globalLockCurrentQueueTotal             = "globalLock.currentQueue.total"
	globalLockCurrentQueueWriters           = "globalLock.currentQueue.writers"
	indexSize                               = "indexSize"
	memoryMapped                            = "memory.mapped"
	memoryResident                          = "memory.resident"
	memoryVirtual                           = "memory.virtual"
	networkBytesIn                          = "network.bytesIn"
	networkBytesOut                         = "network.bytesOut"
	networkNumRequests                      = "network.numRequests"
	opExecutionTimeCommands                 = "op.execution.time.commands"
	opExecutionTimeReads                    = "op.execution.time.reads"
	opExecutionTimeWrites                   = "op.execution.time.writes"
	opcounterCommand                        = "opcounter.command"
	opcounterDelete                         = "opcounter.delete"
	opcounterGetmore                        = "opcounter.getmore"
	opcounterInsert                         = "opcounter.insert"
	opcounterQuery                          = "opcounter.query"
	opcounterUpdate                         = "opcounter.update"
	opcounterReplCommand                    = "opcounterRepl.command"
	opcounterReplDelete                     = "opcounterRepl.delete"
	opcounterReplInsert                     = "opcounterRepl.insert"
	opcounterReplUpdate                     = "opcounterRepl.update"
	operationsScanAndOrder                  = "operationsScanAndOrder"
	oplogMasterLagTimeDiff                  = "oplog.master.lagTimeDiff"
	oplogMasterTime                         = "oplog.master.time"
	oplogRate                               = "oplog.rate"
	oplogSlaveLagMasterTime                 = "oplog.slave.lagMasterTime"
	pageFaults                              = "pageFaults"
	processCPUKernel                        = "process.cpu.kernel"
	processCPUUser                          = "process.cpu.user"
	processNormalizedCPUChildrenKernel      = "process.normalized.cpu.childrenKernel"
	processNormalizedCPUChildrenUser        = "process.normalized.cpu.childrenUser"
	processNormalizedCPUKernel              = "process.normalized.cpu.kernel"
	processNormalizedCPUUser                = "process.normalized.cpu.user"
	queryExecutorScanned                    = "query.executor.scanned"
	queryExecutorScannedObjects             = "query.executor.scannedObjects"
	queryTargetingScannedObjectsPerReturned = "query.targeting.scannedObjectsPerReturned"
	queryTargetingScannedPerReturned        = "query.targeting.scannedPerReturned"
	storageSize                             = "storageSize"
	systemCPUGuest                          = "system.cpu.guest"
	systemCPUIowait                         = "system.cpu.iowait"
	systemCPUIrq                            = "system.cpu.irq"
	systemCPUKernel                         = "system.cpu.kernel"
	systemCPUNice                           = "system.cpu.nice"
	systemCPUSoftirq                        = "system.cpu.softirq"
	systemCPUSteal                          = "system.cpu.steal"
	systemCPUUser                           = "system.cpu.user"
	systemNormalizedCPUGuest                = "system.normalized.cpu.guest"
	systemNormalizedCPUIowait               = "system.normalized.cpu.iowait"
	systemNormalizedCPUIrq                  = "system.normalized.cpu.irq"
	systemNormalizedCPUKernel               = "system.normalized.cpu.kernel"
	systemNormalizedCPUNice                 = "system.normalized.cpu.nice"
	systemNormalizedCPUSoftirq              = "system.normalized.cpu.softirq"
	systemNormalizedCPUSteal                = "system.normalized.cpu.steal"
	systemNormalizedCPUUser                 = "system.normalized.cpu.user"
	ticketsAvailableReads                   = "tickets.available.reads"
	ticketsAvailableWrite                   = "tickets.available.write"
)

var metricSet = map[string]monitors.MetricInfo{
	assertsMsg:                              {Type: datapoint.Count, Group: groupMongodbmetrics},
	assertsRegular:                          {Type: datapoint.Count, Group: groupMongodbmetrics},
	assertsUser:                             {Type: datapoint.Count, Group: groupMongodbmetrics},
	assertsWarning:                          {Type: datapoint.Count, Group: groupMongodbmetrics},
	cacheBytesReadInto:                      {Type: datapoint.Count, Group: groupWiredTiger},
	cacheBytesWrittenFrom:                   {Type: datapoint.Count, Group: groupWiredTiger},
	cacheDirtyBytes:                         {Type: datapoint.Gauge, Group: groupWiredTiger},
	cacheUsedBytes:                          {Type: datapoint.Gauge, Group: groupWiredTiger},
	connectionsCurrent:                      {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	cursorsTimedOut:                         {Type: datapoint.Count, Group: groupMongodbmetrics},
	cursorsTotalOpen:                        {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	dataSize:                                {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	diskPartitionIopsRead:                   {Type: datapoint.Count, Group: groupHardwaremetrics},
	diskPartitionIopsTotal:                  {Type: datapoint.Count, Group: groupHardwaremetrics},
	diskPartitionIopsWrite:                  {Type: datapoint.Count, Group: groupHardwaremetrics},
	diskPartitionLatencyRead:                {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	diskPartitionLatencyWrite:               {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	diskPartitionSpaceFree:                  {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	diskPartitionSpacePercentFree:           {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	diskPartitionSpacePercentUsed:           {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	diskPartitionSpaceUsed:                  {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	diskPartitionUtilization:                {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	documentMetricsDeleted:                  {Type: datapoint.Count, Group: groupMongodbmetrics},
	documentMetricsInserted:                 {Type: datapoint.Count, Group: groupMongodbmetrics},
	documentMetricsReturned:                 {Type: datapoint.Count, Group: groupMongodbmetrics},
	documentMetricsUpdated:                  {Type: datapoint.Count, Group: groupMongodbmetrics},
	globalLockCurrentQueueReaders:           {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	globalLockCurrentQueueTotal:             {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	globalLockCurrentQueueWriters:           {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	indexSize:                               {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	memoryMapped:                            {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	memoryResident:                          {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	memoryVirtual:                           {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	networkBytesIn:                          {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	networkBytesOut:                         {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	networkNumRequests:                      {Type: datapoint.Count, Group: groupMongodbmetrics},
	opExecutionTimeCommands:                 {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	opExecutionTimeReads:                    {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	opExecutionTimeWrites:                   {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	opcounterCommand:                        {Type: datapoint.Count, Group: groupMongodbmetrics},
	opcounterDelete:                         {Type: datapoint.Count, Group: groupMongodbmetrics},
	opcounterGetmore:                        {Type: datapoint.Count, Group: groupMongodbmetrics},
	opcounterInsert:                         {Type: datapoint.Count, Group: groupMongodbmetrics},
	opcounterQuery:                          {Type: datapoint.Count, Group: groupMongodbmetrics},
	opcounterUpdate:                         {Type: datapoint.Count, Group: groupMongodbmetrics},
	opcounterReplCommand:                    {Type: datapoint.Count, Group: groupMongodbmetrics},
	opcounterReplDelete:                     {Type: datapoint.Count, Group: groupMongodbmetrics},
	opcounterReplInsert:                     {Type: datapoint.Count, Group: groupMongodbmetrics},
	opcounterReplUpdate:                     {Type: datapoint.Count, Group: groupMongodbmetrics},
	operationsScanAndOrder:                  {Type: datapoint.Count, Group: groupMongodbmetrics},
	oplogMasterLagTimeDiff:                  {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	oplogMasterTime:                         {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	oplogRate:                               {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	oplogSlaveLagMasterTime:                 {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	pageFaults:                              {Type: datapoint.Count, Group: groupMongodbmetrics},
	processCPUKernel:                        {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	processCPUUser:                          {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	processNormalizedCPUChildrenKernel:      {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	processNormalizedCPUChildrenUser:        {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	processNormalizedCPUKernel:              {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	processNormalizedCPUUser:                {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	queryExecutorScanned:                    {Type: datapoint.Count, Group: groupMongodbmetrics},
	queryExecutorScannedObjects:             {Type: datapoint.Count, Group: groupMongodbmetrics},
	queryTargetingScannedObjectsPerReturned: {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	queryTargetingScannedPerReturned:        {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	storageSize:                             {Type: datapoint.Gauge, Group: groupMongodbmetrics},
	systemCPUGuest:                          {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemCPUIowait:                         {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemCPUIrq:                            {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemCPUKernel:                         {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemCPUNice:                           {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemCPUSoftirq:                        {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemCPUSteal:                          {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemCPUUser:                           {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemNormalizedCPUGuest:                {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemNormalizedCPUIowait:               {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemNormalizedCPUIrq:                  {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemNormalizedCPUKernel:               {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemNormalizedCPUNice:                 {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemNormalizedCPUSoftirq:              {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemNormalizedCPUSteal:                {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	systemNormalizedCPUUser:                 {Type: datapoint.Gauge, Group: groupHardwaremetrics},
	ticketsAvailableReads:                   {Type: datapoint.Gauge, Group: groupWiredTiger},
	ticketsAvailableWrite:                   {Type: datapoint.Gauge, Group: groupWiredTiger},
}

var defaultMetrics = map[string]bool{
	connectionsCurrent:            true,
	dataSize:                      true,
	globalLockCurrentQueueReaders: true,
	globalLockCurrentQueueWriters: true,
	indexSize:                     true,
	memoryMapped:                  true,
	memoryResident:                true,
	memoryVirtual:                 true,
	networkBytesIn:                true,
	networkBytesOut:               true,
	networkNumRequests:            true,
	opcounterDelete:               true,
	opcounterInsert:               true,
	opcounterQuery:                true,
	opcounterUpdate:               true,
	pageFaults:                    true,
	storageSize:                   true,
}

var groupMetricsMap = map[string][]string{
	groupWiredTiger: []string{
		cacheBytesReadInto,
		cacheBytesWrittenFrom,
		cacheDirtyBytes,
		cacheUsedBytes,
		ticketsAvailableReads,
		ticketsAvailableWrite,
	},
	groupHardwaremetrics: []string{
		diskPartitionIopsRead,
		diskPartitionIopsTotal,
		diskPartitionIopsWrite,
		diskPartitionLatencyRead,
		diskPartitionLatencyWrite,
		diskPartitionSpaceFree,
		diskPartitionSpacePercentFree,
		diskPartitionSpacePercentUsed,
		diskPartitionSpaceUsed,
		diskPartitionUtilization,
		processCPUKernel,
		processCPUUser,
		processNormalizedCPUChildrenKernel,
		processNormalizedCPUChildrenUser,
		processNormalizedCPUKernel,
		processNormalizedCPUUser,
		systemCPUGuest,
		systemCPUIowait,
		systemCPUIrq,
		systemCPUKernel,
		systemCPUNice,
		systemCPUSoftirq,
		systemCPUSteal,
		systemCPUUser,
		systemNormalizedCPUGuest,
		systemNormalizedCPUIowait,
		systemNormalizedCPUIrq,
		systemNormalizedCPUKernel,
		systemNormalizedCPUNice,
		systemNormalizedCPUSoftirq,
		systemNormalizedCPUSteal,
		systemNormalizedCPUUser,
	},
	groupMongodbmetrics: []string{
		assertsMsg,
		assertsRegular,
		assertsUser,
		assertsWarning,
		connectionsCurrent,
		cursorsTimedOut,
		cursorsTotalOpen,
		dataSize,
		documentMetricsDeleted,
		documentMetricsInserted,
		documentMetricsReturned,
		documentMetricsUpdated,
		globalLockCurrentQueueReaders,
		globalLockCurrentQueueTotal,
		globalLockCurrentQueueWriters,
		indexSize,
		memoryMapped,
		memoryResident,
		memoryVirtual,
		networkBytesIn,
		networkBytesOut,
		networkNumRequests,
		opExecutionTimeCommands,
		opExecutionTimeReads,
		opExecutionTimeWrites,
		opcounterCommand,
		opcounterDelete,
		opcounterGetmore,
		opcounterInsert,
		opcounterQuery,
		opcounterUpdate,
		opcounterReplCommand,
		opcounterReplDelete,
		opcounterReplInsert,
		opcounterReplUpdate,
		operationsScanAndOrder,
		oplogMasterLagTimeDiff,
		oplogMasterTime,
		oplogRate,
		oplogSlaveLagMasterTime,
		pageFaults,
		queryExecutorScanned,
		queryExecutorScannedObjects,
		queryTargetingScannedObjectsPerReturned,
		queryTargetingScannedPerReturned,
		storageSize,
	},
}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "mongodbatlas",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         false,
}
