blank_issues_enabled: false
contact_links:
  - name: Migrate from SignalFx Smart Agent to the Splunk Distribution of OpenTelemetry Collector
    url: https://docs.splunk.com/Observability/gdi/opentelemetry/smart-agent-migration-to-otel-collector.html
    about: |
      The SignalFx Smart Agent has reached End of Support.
      Smart Agent monitors are available and supported through the Smart Agent receiver in the Splunk Distribution of OpenTelemetry Collector.
