# How often to execute the pipeline.
# interval: 10

# Default pipeline to run.
# pipeline: docker

# Whether to poll plugin configuration files for changes.
# fileWatching: true

# If hostname is unset collectd determines the hostname at runtime.
# hostname:

# Extra dimensions to be included when reporting metrics.
# dimensions:
#   name: value

# Metric ingest URL.
# ingestURL: https://ingest.signalfx.com

stores:
    fs:
        type: filesystem
        # Number of seconds before polling configuration files for changes.
        interval: 5

plugins:
    file:
        plugin: observers/file
        path: /etc/signalfx/service_instances.json

    collectd:
        plugin: monitors/collectd
        confFile: /etc/collectd/collectd.conf
        templates:
            builtins: /etc/signalfx/collectd/templates
        pluginsDir: /usr/share/collectd
        staticPlugins:
            writehttp-default:
                plugin: writehttp
            signalfx-default:
                plugin: signalfx
            docker-default:
                plugin: docker
                hostUrl: unix:///var/run/docker.sock

    debug:
        plugin: filters/debug

    proxy:
        plugin: filters/proxy

    integrations:
        plugin: filters/integrations
        builtins: /etc/signalfx/integrations
        overrides: /etc/signalfx/overrides

pipelines:
    file:
    - file
    - proxy
    - collectd
