pipeline: kubernetes

plugins:
  kubernetes:
      plugin: observers/kubernetes
      # hostUrl: https://<hostname>:10250
      # tls:
      #   # Whether to ignore SSL certification validation errors.
      #   skipVerify: false

  k8sMonitor:
    plugin: monitors/kubernetes

  integrations:
    overrides: /mnt/integrations

  collectd:
    templates:
      builtins: /etc/signalfx/collectd/templates
      overrides: /mnt/templates
    staticPlugins:
      docker-default:
        extraDimensions:
          container_image: inspect:Config.Image
          container_name: inspect:Config.Labels['io.kubernetes.container.name']
          kubernetes_pod_name: inspect:Config.Labels['io.kubernetes.pod.name']
          kubernetes_pod_namespace: inspect:Config.Labels['io.kubernetes.pod.namespace']

  cadvisor:
    plugin: monitors/cadvisor
    dataSendRate: 30
    cadvisorURL: http://localhost:4194

pipelines:
    kubernetes:
    - kubernetes
    - k8sMonitor
    - integrations
    - proxy
    - collectd
