// Code generated by monitor-code-gen. DO NOT EDIT.

package volumes

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "kubernetes-volumes"

var groupSet = map[string]bool{}

const (
	kubernetesVolumeAvailableBytes = "kubernetes.volume_available_bytes"
	kubernetesVolumeCapacityBytes  = "kubernetes.volume_capacity_bytes"
)

var metricSet = map[string]monitors.MetricInfo{
	kubernetesVolumeAvailableBytes: {Type: datapoint.Gauge},
	kubernetesVolumeCapacityBytes:  {Type: datapoint.Gauge},
}

var defaultMetrics = map[string]bool{}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "kubernetes-volumes",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         true,
}
