FROM debian:wheezy-slim

RUN apt-get update &&\
    apt-get install -yq ca-certificates procps wget

COPY socat /bin/socat

# Insert our fake certs to the system bundle so they are trusted
COPY certs/*.signalfx.com.* /
RUN cat /*.cert >> /etc/ssl/certs/ca-certificates.crt

#RUN  update-rc.d -f $DAEMON remove

CMD ["/sbin/init"]
