FROM debian:wheezy-slim

RUN apt-get update &&\
    apt-get install -yq ca-certificates procps wget libcap2-bin apt-transport-https

COPY socat /bin/socat

# Insert our fake certs to the system bundle so they are trusted
COPY certs/*.signalfx.com.* /
RUN cat /*.cert >> /etc/ssl/certs/ca-certificates.crt

CMD ["/sbin/init"]
