FROM centos:6

# Centos 6 is EOL; update yum repo for vault
RUN sed -i '/^mirrorlist.*/d' /etc/yum.repos.d/CentOS-Base.repo
RUN sed -i 's|^#baseurl=http://mirror.centos.org/\(.*\)|baseurl=http://vault.centos.org/\1|' /etc/yum.repos.d/CentOS-Base.repo

RUN yum install -y upstart initscripts

COPY socat /bin/socat

# Insert our fake certs to the system bundle so they are trusted
COPY certs/*.signalfx.com.* /
RUN cat /*.cert >> /etc/pki/tls/certs/ca-bundle.crt

COPY init-fake.conf /etc/init/fake-container-events.conf

CMD ["/sbin/init", "-v"]
