// Code generated by monitor-code-gen. DO NOT EDIT.

package cpu

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "cpu"

var groupSet = map[string]bool{}

const (
	cpuUtilization        = "cpu.utilization"
	cpuUtilizationPerCore = "cpu.utilization_per_core"
)

var metricSet = map[string]monitors.MetricInfo{
	cpuUtilization:        {Type: datapoint.Gauge},
	cpuUtilizationPerCore: {Type: datapoint.Gauge},
}

var defaultMetrics = map[string]bool{
	cpuUtilization: true,
}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:       "cpu",
	DefaultMetrics:    defaultMetrics,
	Metrics:           metricSet,
	MetricsExhaustive: false,
	Groups:            groupSet,
	GroupMetricsMap:   groupMetricsMap,
	SendAll:           false,
}
