// Code generated by monitor-code-gen. DO NOT EDIT.

package cpu

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "cpu"

const (
	groupPerCore = "per_core"
)

var groupSet = map[string]bool{
	groupPerCore: true,
}

const (
	cpuUtilization        = "cpu.utilization"
	cpuUtilizationPerCore = "cpu.utilization_per_core"
)

var metricSet = map[string]monitors.MetricInfo{
	cpuUtilization:        {Type: datapoint.Gauge},
	cpuUtilizationPerCore: {Type: datapoint.Gauge, Group: groupPerCore},
}

var defaultMetrics = map[string]bool{
	cpuUtilization: true,
}

var groupMetricsMap = map[string][]string{
	groupPerCore: []string{
		cpuUtilizationPerCore,
	},
}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "cpu",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         false,
}
