fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.24.0"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt"
      ref: "7.0.0"

