FROM amazonlinux:1

ENV container docker

RUN yum install -y upstart procps initscripts

RUN curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && \
    python /tmp/get-pip.py pip==20.0.2

ARG ANSIBLE_VERSION='==2.4.0'
RUN pip install ansible${ANSIBLE_VERSION}

VOLUME [ "/sys/fs/cgroup" ]

COPY deployments/ansible/* /opt/playbook/
COPY tests/deployments/ansible/images/inventory.ini /opt/playbook/
COPY tests/deployments/ansible/images/playbook.yml /opt/playbook/
COPY tests/packaging/images/init-fake.conf /etc/init/fake-container-events.conf

CMD ["/sbin/init"]
