#!/bin/bash

set -eo pipefail

apk add --no-cache jq
curl -LOk https://github.com/hairyhenderson/gomplate/releases/download/v3.4.0/gomplate_linux-amd64
mv gomplate_linux-amd64 /usr/bin/gomplate
chmod +x /usr/bin/gomplate
make signalfx-agent
bash -ec "make docs && git diff --exit-code" || \
    (echo 'Autogenerated docs and/or the selfdescribe.json file are not in sync with their source! If you directly edited a doc file, please move the changes to the source where the doc is generated from (use grep to find where based on existing doc content). In either case, you need to run `make docs` in the dev image and commit those changes.' && exit 1)
