---
# Source: signalfx-agent/templates/configmap-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: signalfx-agent
  namespace: MY_AGENT_NAMESPACE
  labels:
    app: signalfx-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: signalfx-agent
subjects:
- kind: ServiceAccount
  name: signalfx-agent
  namespace: MY_AGENT_NAMESPACE
