#!/bin/bash

# Connects to the neoagent diagnostic socket that will dump information about
# the current state of the agent.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
bundle_dir=$SCRIPT_DIR/..

# We have to do a bunch of linker magic so this works on standalone
export LD_LIBRARY_PATH=$bundle_dir/lib
loader=$bundle_dir/lib64/ld-linux-x86-64.so.2

exec $loader $bundle_dir/bin/nc.openbsd -U $bundle_dir/run/signalfx.sock
