#!/bin/bash

set -exuo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT_DIR/common.sh

AGENT_IMAGE_NAME=${AGENT_IMAGE_NAME:-"quay.io/signalfx/signalfx-agent-dev"}

AGENT_VERSION=${AGENT_VERSION:-$($SCRIPT_DIR/current-version)}

if [[ "${BUILD_IMAGE:-yes}" = "yes" ]]; then
  do_docker_build ${AGENT_IMAGE_NAME} ${AGENT_VERSION} final-image
fi

if [[ -n ${BUILD_BUNDLE-} ]]
then
  OUTPUT=${OUTPUT:-signalfx-agent-${AGENT_VERSION}.tar.gz}
  output_tar=$(basename $OUTPUT .gz)

  cid=$(docker create ${AGENT_IMAGE_NAME}:$AGENT_VERSION true)
  tmpdir=$(mktemp -d)
  mkdir $tmpdir/signalfx-agent
  trap "docker rm -f $cid; rm -rf $tmpdir; rm -f $output_tar" EXIT

  docker export $cid | tar -C $tmpdir/signalfx-agent -xf -
  rm -rf $tmpdir/signalfx-agent/{proc,sys,dev,etc} $tmpdir/signalfx-agent/.dockerenv
  (cd $tmpdir/signalfx-agent/bin && ln -sf signalfx-agent agent-status)
  curdir=$(pwd)
  (cd $tmpdir && tar -zcf ${curdir}/${output_tar}.gz *)
fi

if [[ "${PUSH-}" = "yes" ]]
then
    docker push ${AGENT_IMAGE_NAME}:${AGENT_VERSION}
fi
