#!/bin/bash

set -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT_DIR/common.sh

AGENT_IMAGE_NAME=${AGENT_IMAGE_NAME:-"quay.io/signalfuse/signalfx-agent"}

TAG=${AGENT_VERSION:-$($SCRIPT_DIR/current-version)}

do_docker_build ${AGENT_IMAGE_NAME} ${TAG} final-image

if [[ -n $BUILD_BUNDLE ]]
then
  OUTPUT=${OUTPUT:-signalfx-agent.tar.gz}
  output_tar=$(basename $OUTPUT .gz)

  cid=$(docker create ${AGENT_IMAGE_NAME}:$TAG true)
  tmpdir=$(mktemp -d)
  mkdir $tmpdir/signalfx-agent
  trap "docker rm -f $cid; rm -rf $tmpdir; rm -f $output_tar" EXIT

  docker export $cid | tar -C $tmpdir/signalfx-agent -xf -
  rm -rf $tmpdir/signalfx-agent/{proc,sys,dev,etc} $tmpdir/signalfx-agent/.dockerenv
  tar -C $tmpdir -zcf $output_tar.gz .
fi

if [[ "$BUILD_PUBLISH" = "True" ]]
then
    docker push ${AGENT_IMAGE_NAME}:${TAG}
fi
