#!/bin/bash

set -exuo pipefail

operating_system=${1:-"linux"}

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT_DIR/common.sh

agent_version=$($SCRIPT_DIR/current-version)

image_name=signalfx-agent-binary-${operating_system}
image_tag=${agent_version}

do_docker_build ${image_name} ${image_tag} agent-builder $agent_version ${operating_system}

OUTPUT_DIR=${OUTPUT_DIR:-$SCRIPT_DIR/..}

cid=$(docker create ${image_name}:${image_tag} true)
trap "docker rm -f $cid" EXIT

if [ "$operating_system" = "windows" ] ; then
  extension=".exe"
fi
  
docker cp $cid:/usr/bin/signalfx-agent  $OUTPUT_DIR/signalfx-agent${extension-""}
