#!/bin/bash

# Converts a raw collectd template to a go file with the template as a variable
# named "CollectdTemplate".  Should be called from the directory of the monitor
# package.

template_filename=$1
target_file=${2:-template.go}

package=$(basename $(pwd))

cat <<-EOH > $target_file
package $package

import "text/template"
import "github.com/signalfx/neo-agent/monitors/collectd/templating"

var CollectdTemplate = template.Must(templating.InjectTemplateFuncs(template.New("$package")).Parse(\`
$(cat $template_filename)
\`))
EOH
