#!/bin/bash

# Determines the current version form the git tags in the repo. In between
# releases, the version is the previous release suffixed with "-post".

strip_v() {
	sed -e 's/^v//' <<< $1
}

strip_pkg() {
  sed -Ee 's/-(deb|rpm)[0-9]+//' <<< $1
}

SCRIPTS_DIR="$( cd "$( dirname ${BASH_SOURCE[0]} )" && pwd )"
REPO_DIR="$( cd "$SCRIPTS_DIR/.." && pwd )"

tag="$( git -C "$REPO_DIR" describe --abbrev=0 --tags --exact-match --match 'v[0-9]*' 2>/dev/null || true )"

if test -z $tag || [[ $tag =~ (deb|rpm) ]]
then
	tag="$( git ls-remote --refs --tags -q | tail -n 1 | awk -F/ '{ print $3 }' )-post"
fi

if test -z $tag
then
  echo "Could not determine version" >&2
  exit 1
fi

strip_pkg $(strip_v $tag)
