#!/bin/bash

# Determines the current version form the git tags in the repo. In between
# releases, the version is the previous release suffixed with "-post".

strip_v() {
	sed -e 's/^v//' <<< $1
}

latest_tag="git describe --abbrev=0 --tags --exclude *deb* --exclude *rpm*"

tag=$($latest_tag --exact-match 2>/dev/null)

if test -z $tag
then
	tag=$($latest_tag)-post
fi

if test -z $tag
then
  echo "Could not determine version" >&2
  exit 1
fi

strip_v $tag
