#!/bin/bash

set -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT_DIR/common.sh

COLLECTD_VERSION=${COLLECTD_VERSION} COLLECTD_COMMIT=${COLLECTD_COMMIT} do_docker_build signalfx-agent-dev-cache stage-agent-builder agent-builder latest

COLLECTD_VERSION=${COLLECTD_VERSION} COLLECTD_COMMIT=${COLLECTD_COMMIT} do_docker_build signalfx-agent-dev-cache stage-final-image final-image latest

target_arch="amd64"
if [ "$(uname -m)" == "aarch64" ]; then
    target_arch="arm64"
fi

docker build -t signalfx-agent-dev:latest --build-arg TARGET_ARCH=${target_arch} -f ${SCRIPT_DIR}/../Dockerfile.dev ${SCRIPT_DIR}/../
