#!/bin/bash
#
# Usage: make-monitor-doc <monitor type>
#
# Generates markdown file for a monitor.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT_DIR/code-gen-helpers.sh

mon_dir=$SCRIPT_DIR/../docs/monitors
mkdir -p $mon_dir

monitorType=$1

j ".Monitors[] | select(.monitorType==\"${monitorType}\")" | \
    inject_to_obj "doc_types" "$doc_types" | \
    gomplate --file $SCRIPT_DIR/docs/templates/monitor-page.md.tmpl --datasource monitor=stdin:///monitor.json > $mon_dir/${monitorType//\//-}.md