#!/bin/bash

set -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT_DIR/common.sh

dockerfile=$SCRIPT_DIR/.Dockerfile.signalfx-agent-dev

cat $SCRIPT_DIR/../Dockerfile > $dockerfile

cat <<-EOH >> $dockerfile

FROM final-image

COPY --from=godeps /go/src/github.com/signalfx/neo-agent/vendor src/github.com/signalfx/neo-agent/vendor
COPY --from=godeps /go/pkg /go/pkg

COPY --from=agent-builder /usr/ /tmp/usr-agent-buider
COPY --from=godeps /usr/ /tmp/usr-godeps
COPY --from=collectd /usr/ /tmp/usr-collectd
COPY --from=collectd /etc/ /tmp/etc-collectd

WORKDIR /tmp
RUN wget https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz &&\
    tar -xf go1.9.2* &&\
    mv go /usr/local

RUN cp -ra /tmp/usr-collectd/* /usr/ &&\
    cd /usr/src/collectd &&\
    make install

RUN cp /tmp/usr-godeps/bin/dep /usr/bin/

RUN pip install ipython==5 ipdb

RUN apt install -y \
      libzmq5-dev \
      inotify-tools \
      autoconf \
      automake \
      autotools-dev \
      bison \
      build-essential

ENV PATH=$PATH:/usr/local/go/bin:/go/bin GOPATH=/go

RUN go get -u github.com/golang/lint/golint
RUN go get -u github.com/kisielk/errcheck

WORKDIR /go/src/github.com/signalfx/neo-agent

CMD ["/bin/bash"]
EOH

do_docker_build signalfx-agent-dev $dockerfile
