#!/bin/sh

# The interpreter on all binary files will be set to the bundled interpreter.

set -eu

# The final place where the files will live
root=${1}
# The place where the files currently live when this script is run
tmproot=${2-$root}
interpreter="${root%/}/bin/ld-linux.so"

echo "Setting interpreter on ${tmproot%/}/bin/* to $interpreter"

for f in ${tmproot%/}/bin/* ${tmproot%/}/jre/bin/*; do
  ${tmproot%/}/bin/patchelf --set-interpreter $interpreter $f 2>/dev/null || true
done
