#!/bin/bash

# This is a convenience script that makes using the dev image a bit easier.
# Once you have built the dev image with `make dev-image`, run this script to
# pull the vendor dir out of the image to your local workspace.  That way, when
# you share the local workspace into the dev container, you won't have to pull
# the vendor directory again.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cid=$(docker run -d signalfx-agent-dev true)
docker cp $cid:/go/src/github.com/signalfx/signalfx-agent/vendor $SCRIPT_DIR/../vendor
docker rm -f $cid

echo 'Vendor directory is now setup in local workspace, you can run "make run-dev-image" now to start development.'
