# A centos7 image with systemd enabled.  Must be run with:
# `--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro`
# flags
FROM centos:7

ARG CHEF_RPM=https://packages.chef.io/files/stable/chef/12.8.1/el/7/chef-12.8.1-1.el7.x86_64.rpm

ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = \
    "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN yum install -y $CHEF_RPM

VOLUME ["/sys/fs/cgroup", "/opt/cookbooks/"]

CMD ["/usr/sbin/init"]
