---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
data:
  haproxy.cfg: |
    global
      daemon
      stats socket :9000
      stats timeout 2m
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy-deployment
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: haproxy-conf
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
      volumes:
        - name: haproxy-conf
          configMap:
            name: haproxy-configmap
