---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-test
  labels:
    app: curl-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-test
  template:
    metadata:
      labels:
        app: curl-test
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: byrnedo/alpine-curl:0.1
        imagePullPolicy: IfNotPresent
        name: curl
        # This is purely to give the k8s-api observer something to discover
        ports:
          - containerPort: 80
            name: http
