monitors:
- dimensions:
  doc: |
    Pulls container stats from the Docker Engine.  We
    strongly recommend using the
    [docker-container-stats](./docker-container-stats.md) monitor instead, as it
    will scale to large number of containers much better.

    See https://github.com/signalfx/docker-collectd-plugin.
  groups:
    blkio:
      description: BlockIO metrics
    cpu:
      description: CPU metrics
    memory:
      description: Memory metrics
    network:
      description: Network metrics
  metrics:
    blkio.io_service_bytes_recursive.read:
      description: Volume, in bytes, of reads from block devices
      default: true
      type: cumulative
      group: blkio
    blkio.io_service_bytes_recursive.write:
      description: Volume, in bytes, of writes to block devices
      default: true
      type: cumulative
      group: blkio
    blkio.io_service_bytes_recursive.total:
      description: Total volume, in bytes, of all block I/O
      default: true
      type: cumulative
      group: blkio
    blkio.io_service_bytes_recursive.sync:
      description: Volume, in bytes, of synchronous block I/O
      default: true
      type: cumulative
      group: blkio
    blkio.io_service_bytes_recursive.async:
      description: Volume, in bytes, of asynchronous block I/O
      default: true
      type: cumulative
      group: blkio
    cpu.usage.system:
      description: Jiffies of CPU time used by the system
      default: true
      type: gauge
      group: cpu
    cpu.usage.usermode:
      description: Jiffies of CPU time spent in user mode by the container
      default: true
      type: cumulative
      group: cpu
    cpu.usage.kernelmode:
      description: Jiffies of CPU time spent in kernel mode by the container
      default: true
      type: cumulative
      group: cpu
    cpu.usage.total:
      description: Jiffies of CPU time used by the container
      default: true
      type: gauge
      group: cpu
    memory.usage.limit:
      description: Memory usage limit of the container, in bytes
      default: true
      type: gauge
      group: memory
    memory.usage.max:
      description: Maximum measured memory usage of the container, in bytes
      default: true
      type: gauge
      group: memory
    memory.usage.total:
      description: Bytes of memory used by the container
      default: true
      type: gauge
      group: memory
    network.usage.rx_bytes:
      description: Bytes received by the container via its network interface
      default: false
      type: cumulative
      group: network
    network.usage.rx_dropped:
      description: Number of inbound network packets dropped by the container
      default: false
      type: cumulative
      group: network
    network.usage.rx_errors:
      description: Errors receiving network packets
      default: false
      type: cumulative
      group: network
    network.usage.rx_packets:
      description: Network packets received by the container via its network interface
      default: false
      type: cumulative
      group: network
    network.usage.tx_bytes:
      description: Bytes sent by the container via its network interface
      default: false
      type: cumulative
      group: network
    network.usage.tx_dropped:
      description: Number of outbound network packets dropped by the container
      default: false
      type: cumulative
      group: network
    network.usage.tx_errors:
      description: Errors sending network packets
      default: false
      type: cumulative
      group: network
    network.usage.tx_packets:
      description: Network packets sent by the container via its network interface
      default: false
      type: cumulative
      group: network
  monitorType: collectd/docker
  properties:
