FROM centos:8

ENV container docker

RUN dnf install -y systemd procps initscripts python3
RUN alternatives --set python /usr/bin/python3
RUN dnf install -y https://repo.saltstack.com/py3/redhat/salt-py3-repo-2019.2.el8.noarch.rpm && \
    yum install -y salt-minion

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = \
    "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN sed -i "s|#file_client:.*|file_client: local|" /etc/salt/minion

COPY deployments/salt/signalfx-agent/ /srv/salt/signalfx-agent/
COPY tests/deployments/salt/images/top.sls /srv/salt/top.sls
COPY tests/deployments/salt/images/top.sls /srv/pillar/top.sls
RUN systemctl disable salt-minion

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
