// Code generated by monitor-code-gen. DO NOT EDIT.

package jenkins

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "jenkins"

const (
	groupHealth      = "health"
	groupJob         = "job"
	groupNode        = "node"
	groupNodeStatus  = "node/status"
	groupSlaveStatus = "slave/status"
)

var groupSet = map[string]bool{
	groupHealth:      true,
	groupJob:         true,
	groupNode:        true,
	groupNodeStatus:  true,
	groupSlaveStatus: true,
}

const (
	jenkinsJobDuration              = "jenkins.job.duration"
	jenkinsNodeExecutorCount        = "jenkins.node.executor.count"
	jenkinsNodeExecutorInUse        = "jenkins.node.executor.in-use"
	jenkinsNodeHealthCheckScore     = "jenkins.node.health-check.score"
	jenkinsNodeHealthDiskSpace      = "jenkins.node.health.disk.space"
	jenkinsNodeHealthPlugins        = "jenkins.node.health.plugins"
	jenkinsNodeHealthTemporarySpace = "jenkins.node.health.temporary.space"
	jenkinsNodeHealthThreadDeadlock = "jenkins.node.health.thread-deadlock"
	jenkinsNodeOnlineStatus         = "jenkins.node.online.status"
	jenkinsNodeQueueSize            = "jenkins.node.queue.size"
	jenkinsNodeSlaveOnlineStatus    = "jenkins.node.slave.online.status"
	jenkinsNodeVMMemoryHeapUsage    = "jenkins.node.vm.memory.heap.usage"
	jenkinsNodeVMMemoryNonHeapUsed  = "jenkins.node.vm.memory.non-heap.used"
	jenkinsNodeVMMemoryTotalUsed    = "jenkins.node.vm.memory.total.used"
)

var metricSet = map[string]monitors.MetricInfo{
	jenkinsJobDuration:              {Type: datapoint.Gauge, Group: groupJob},
	jenkinsNodeExecutorCount:        {Type: datapoint.Gauge, Group: groupNode},
	jenkinsNodeExecutorInUse:        {Type: datapoint.Gauge, Group: groupNode},
	jenkinsNodeHealthCheckScore:     {Type: datapoint.Gauge, Group: groupNode},
	jenkinsNodeHealthDiskSpace:      {Type: datapoint.Gauge, Group: groupHealth},
	jenkinsNodeHealthPlugins:        {Type: datapoint.Gauge, Group: groupHealth},
	jenkinsNodeHealthTemporarySpace: {Type: datapoint.Gauge, Group: groupHealth},
	jenkinsNodeHealthThreadDeadlock: {Type: datapoint.Gauge, Group: groupHealth},
	jenkinsNodeOnlineStatus:         {Type: datapoint.Gauge, Group: groupNodeStatus},
	jenkinsNodeQueueSize:            {Type: datapoint.Gauge, Group: groupNode},
	jenkinsNodeSlaveOnlineStatus:    {Type: datapoint.Gauge, Group: groupSlaveStatus},
	jenkinsNodeVMMemoryHeapUsage:    {Type: datapoint.Gauge, Group: groupNode},
	jenkinsNodeVMMemoryNonHeapUsed:  {Type: datapoint.Gauge, Group: groupNode},
	jenkinsNodeVMMemoryTotalUsed:    {Type: datapoint.Gauge, Group: groupNode},
}

var defaultMetrics = map[string]bool{
	jenkinsJobDuration:              true,
	jenkinsNodeExecutorCount:        true,
	jenkinsNodeExecutorInUse:        true,
	jenkinsNodeHealthCheckScore:     true,
	jenkinsNodeHealthDiskSpace:      true,
	jenkinsNodeHealthPlugins:        true,
	jenkinsNodeHealthTemporarySpace: true,
	jenkinsNodeHealthThreadDeadlock: true,
	jenkinsNodeOnlineStatus:         true,
	jenkinsNodeQueueSize:            true,
	jenkinsNodeSlaveOnlineStatus:    true,
	jenkinsNodeVMMemoryHeapUsage:    true,
	jenkinsNodeVMMemoryNonHeapUsed:  true,
	jenkinsNodeVMMemoryTotalUsed:    true,
}

var groupMetricsMap = map[string][]string{
	groupHealth: []string{
		jenkinsNodeHealthDiskSpace,
		jenkinsNodeHealthPlugins,
		jenkinsNodeHealthTemporarySpace,
		jenkinsNodeHealthThreadDeadlock,
	},
	groupJob: []string{
		jenkinsJobDuration,
	},
	groupNode: []string{
		jenkinsNodeExecutorCount,
		jenkinsNodeExecutorInUse,
		jenkinsNodeHealthCheckScore,
		jenkinsNodeQueueSize,
		jenkinsNodeVMMemoryHeapUsage,
		jenkinsNodeVMMemoryNonHeapUsed,
		jenkinsNodeVMMemoryTotalUsed,
	},
	groupNodeStatus: []string{
		jenkinsNodeOnlineStatus,
	},
	groupSlaveStatus: []string{
		jenkinsNodeSlaveOnlineStatus,
	},
}

var monitorMetadata = monitors.Metadata{
	MonitorType:       "jenkins",
	DefaultMetrics:    defaultMetrics,
	Metrics:           metricSet,
	MetricsExhaustive: false,
	Groups:            groupSet,
	GroupMetricsMap:   groupMetricsMap,
	SendAll:           false,
}
