name: perf-tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: perf-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RESULT_PATH: testresults
  GO_VERSION: 1.18.7
  PYTHON_VERSION: 3.8.10
  REQUIREMENTS_PATH: "tests/requirements.txt"

jobs:
  perf-tests:
    name: perf-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-v1-go-mod-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}

      - name: go mod download
        run: |
          [[ -d ~/go/pkg/mod ]] && exit 0
          # retry up to 3 times in case of network issues
          for i in $(seq 1 3); do
              go mod download && exit 0
              sleep 10
          done
          exit 1

      - name: Build agent
        run: |
          make signalfx-agent
          echo "AGENT_BIN=$(pwd)/signalfx-agent" >> $GITHUB_ENV

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: v1-pytest-${{ env.PYTHON_VERSION }}-${{ hashFiles(env.REQUIREMENTS_PATH) }}

      - name: Install pytest
        run: pip install -r "${{ env.REQUIREMENTS_PATH }}"

      - name: Run pytest
        env:
          MARKERS: perf_test
          WORKERS: 1
          TESTS_DIR: ./tests
        run: .github/scripts/run-pytest.sh

      - name: Uploading test results
        uses: actions/upload-artifact@v3
        with:
          name: perf-test-results
          path: ~/${{ env.RESULT_PATH }}
